const NAV=[['home','◈','投研总览'],['markets','⌁','市场与指数'],['styles','⇄','风格比较'],['signals','▦','四维信号'],['macro','◉','宏观观察'],['narratives','◇','叙事工作台'],['overview','⊞','信用周期专题'],['chains','⇢','产业传导'],['companies','▤','公司观察池'],['horizon','◷','2027—2028'],['evidence','≡','研究证据'],['sources','⊙','数据与来源']];
const KEY='workbench01-observatory-v1';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=x=>{try{const u=new URL(x);return ['https:','http:'].includes(u.protocol)?u.href:null}catch{return null}};
const country={CN:'中国',US:'美国',HK:'港股',JP:'日本',GLOBAL:'跨市场'};
let storageOK=true, saved={records:[],notes:[],commitments:[],revisions:[]};
try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw&&Array.isArray(raw.records)&&Array.isArray(raw.notes)&&Array.isArray(raw.commitments))saved={...raw,revisions:Array.isArray(raw.revisions)?raw.revisions:[]}}catch{storageOK=false}
const state={page:'home',mode:'real',market:'ALL',chain:'A',panel:null,search:'',companyChain:'ALL',stage:'ALL',sort:'name',range:12,drawer:null};
let lastFocus=null,toastTimer=null;
function persist(){try{localStorage.setItem(KEY,JSON.stringify(saved));return true}catch{storageOK=false;toast('浏览器未允许本地保存，请导出研究记录保留本次修改。');return false}}
function toast(s){const el=document.getElementById('toast');el.textContent=s;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,5000)}
function uid(){return globalThis.crypto?.randomUUID?.()||Date.now()+'-'+Math.random().toString(36).slice(2)}
function fmt(v,d=1){return v===null||v===undefined?'—':Number(v).toLocaleString('zh-CN',{minimumFractionDigits:d,maximumFractionDigits:d})}
function marketBadge(m){return `<span class="badge ${m==='CN'?'cn':m==='US'?'us':''}">${esc(country[m]||m)}</span>`}
function modeBadge(){return state.mode==='demo'?'<span class="badge demo">示例 · 非市场事实</span>':'<span class="badge">研究数据 · 按来源验证</span>'}
function num(v,unit='%',d=1){return `<span class="num">${fmt(v,d)}</span><span class="unit">${esc(unit)}</span>`}
function hash(str){let a=0;for(const c of str)a=(a*31+c.charCodeAt(0))>>>0;return a}
function mockSeries(id,unit='%'){
 const seed=hash(id), base=unit==='天'?50:unit==='倍'?3.2:unit==='点'?49.8:id.includes('top')?65:id.includes('breadth')?49:id.includes('standards')?16:4.2;
 return Array.from({length:24},(_,i)=>({metricId:id,period:`${2023+Math.floor(i/12)}-${String(i%12+1).padStart(2,'0')}-28`,publishedAt:`${2023+Math.floor(i/12)}-${String(i%12+1).padStart(2,'0')}-28`,value:Math.round((base+Math.sin(i*.47+seed%7)*(unit==='天'?6:unit==='倍'?.7:3)+(i-12)*((seed%5-2)*.14))*100)/100,sourceLabel:'合成演示数据',sourceUrl:null,sampleSize:id.includes('breadth')||id.includes('top')||id.includes('ocf')?12:null,notes:'仅用于交互演示，日期与数值均不代表实际发布。'}));
}
function series(m){return state.mode==='demo'?mockSeries(m.id,m.unit):saved.records.filter(r=>r.metricId===m.id).sort((a,b)=>a.period.localeCompare(b.period))}
function latest(m){return series(m).at(-1)}
function metricBy(id){return CFG.metrics.find(m=>m.id===id)}
function spark(rows,color='var(--teal)',large=false){
 if(!rows.length)return `<div class="empty-chart ${large?'chart-lg':''}"><span>尚无已核实序列 · 点击录入或导入数据</span></div>`;
 const rr=rows.slice(-state.range), vals=rr.map(r=>r.value),low=Math.min(...vals),high=Math.max(...vals),pad=Math.max((high-low)*.18,1),min=low-pad,max=high+pad,W=large?490:320,H=large?205:66,left=large?44:0,right=large?12:0,top=10,bottom=large?30:8;
 const xx=i=>left+(rr.length===1?.5:i/(rr.length-1))*(W-left-right), yy=v=>top+(max-v)/(max-min)*(H-top-bottom);
 const points=rr.map((r,i)=>`${xx(i)},${yy(r.value)}`).join(' ');
 const area=`M ${xx(0)} ${H-bottom} L ${points.split(' ').join(' L ')} L ${xx(rr.length-1)} ${H-bottom} Z`;
 let grid='';if(large)for(let k=0;k<4;k++){let v=min+(max-min)*k/3,y=yy(v);grid+=`<line x1="${left}" y1="${y}" x2="${W-right}" y2="${y}" stroke="#e6edf2"/><text x="${left-8}" y="${y+3}" text-anchor="end" fill="#8293a0" font-size="9">${fmt(v)}</text>`}
 return `<svg class="${large?'':'spark'}" viewBox="0 0 ${W} ${H}" role="img" aria-label="${state.mode==='demo'?'合成示例':'已录入'}趋势，共${rr.length}个观察值；最新${fmt(vals.at(-1))}">${grid}<path d="${area}" fill="${color}" opacity=".045"/><polyline points="${points}" fill="none" stroke="${color}" stroke-width="${large?2.5:2}" stroke-linecap="round" stroke-linejoin="round"/><circle cx="${xx(rr.length-1)}" cy="${yy(vals.at(-1))}" r="3" fill="${color}"/>${large?`<text x="${left}" y="${H-5}" fill="#8293a0" font-size="9">${rr[0].period}</text><text x="${W-right}" y="${H-5}" text-anchor="end" fill="#8293a0" font-size="9">${rr.at(-1).period}</text>`:''}</svg>`;
}
function notice(){return `<div class="notice ${state.mode==='demo'?'demo':''}"><span>${state.mode==='demo'?'◉':'○'}</span><span>${state.mode==='demo'?'演示模式：全部曲线、公司数值与分布均为合成示例，不代表市场、公司或历史事实。':'研究数据模式：未连接自动数据源。仅展示你录入或导入的数据；其余保持待接入，不生成市场判断。'}${storageOK?'':' 本地保存不可用，请及时导出。'}</span></div>`}
function marketFilter(options=['ALL','CN','US']){return `<select id="market-filter" aria-label="选择市场">${options.map(m=>`<option value="${m}" ${state.market===m?'selected':''}>${m==='ALL'?'全部市场':country[m]}</option>`).join('')}</select>`}
function pageHead(k,title,sub,actions=''){return `<div class="page-head"><div><div class="eyebrow">${esc(k)}</div><h1>${title}</h1><p class="subtitle">${sub}</p></div><div class="filters">${actions}</div></div>`}
function section(title,action=''){return `<div class="section-head"><h2>${title}</h2>${action}</div>`}
function empty(title,desc){return `<div class="empty-state"><strong>${title}</strong><p>${desc}</p></div>`}
function visibleMetric(m){return state.market==='ALL'||m.market===state.market}
function metricCard(m){const rows=series(m),r=rows.at(-1);return `<button class="card metric-card" data-metric="${m.id}"><div class="card-top"><h3>${esc(m.name)}</h3>${marketBadge(m.market)}</div><div class="metric-row"><div><div class="big-number">${num(r?.value,m.unit)}</div><div class="metric-name">${esc(m.freq)}度 · ${r?esc(r.period):'等待数据'}</div></div><span class="badge ${state.mode==='demo'?'demo':r?'real':''}">${state.mode==='demo'?'示例':r?'已录入':'待接入'}</span></div>${spark(rows,m.market==='CN'?'var(--teal)':'var(--blue)')}<div class="metric-foot"><span>${esc(m.meaning)}</span><span>详情 ↗</span></div></button>`}
function overview(){
 const count=new Set(saved.records.map(r=>r.metricId)).size;
 return pageHead('CREDIT CYCLE / 2027—2028','信用走到哪里，回报留在哪里','沿融资、支出、订单、现金与偿债，观察中美周期的扩散和集中。消费与通胀是传导结果，也是验证条件。',marketFilter()+`<button class="pill" data-nav="evidence">＋ 记录证据</button>`)+
 `<div class="card cycle-map"><div class="map-title"><h2>信用与产业分配的六个观察节点</h2><span class="badge">点选节点下钻</span></div><div class="map-flow">${CFG.panels.map((p,i)=>`<button class="flow-node" data-panel="${p.id}"><span class="dot mono">0${i+1}</span><strong>${p.name}</strong><small>${p.short}</small></button>`).join('')}</div><div class="map-foot"><span>内部现金与外部融资分列 · 龙头与中位数并看 · 已知承诺与情景分开</span><span class="mono">${state.mode==='demo'?'DEMO / 合成示例':`${count} / ${CFG.metrics.length} 条序列已录入`}</span></div></div>`+
 section('两条总命题，一组共同问题')+`<div class="grid-2">${state.market!=='US'?`<article class="card region-thesis"><div class="card-top">${marketBadge('CN')}<span class="badge">待验证命题</span></div><h3 class="thesis-title">政府与政策支出，能否带动自主需求？</h3><p class="thesis-path">政府与企业支出 → 订单、就业与收入 → 居民消费 → 利润回款 → 再投资或偿债</p><div class="line-foot"><span>重点反证：支出增加，但非头部回款与居民收入未跟进。</span><button class="text-btn" data-chain="A">进入中国链条 →</button></div></article>`:''}${state.market!=='CN'?`<article class="card region-thesis us"><div class="card-top">${marketBadge('US')}<span class="badge">待验证命题</span></div><h3 class="thesis-title">集中投入，能否越过再融资压力向外扩散？</h3><p class="thesis-path">通胀与融资条件 → 新旧债重定价 → 企业投资和居民支出 → 经营回报与信用损失</p><div class="line-foot"><span>重点反证：大型企业扩张，一般企业和居民压力仍上升。</span><button class="text-btn" data-chain="E">进入美国链条 →</button></div></article>`:''}</div>`+
 section('核心观测面板',`<span class="muted" style="font-size:11px">每个面板同时检验事实、传导与反证</span>`)+`<div class="grid-3">${CFG.panels.map((p,i)=>{const mm=CFG.metrics.filter(m=>m.panel===p.id&&visibleMetric(m)),m=mm[0],r=latest(m);return `<button class="card metric-card" data-panel="${p.id}"><div class="card-top"><h3><span class="panel-index">0${i+1}</span>${p.name}</h3><span class="badge">${mm.length} 条</span></div><p class="card-sub">${p.question}</p><div class="metric-row"><div><div class="big-number">${num(r?.value,m.unit)}</div><div class="metric-name">${m.name} · ${country[m.market]}</div></div><span class="badge ${state.mode==='demo'?'demo':''}">${state.mode==='demo'?'示例':r?'已录入':'待接入'}</span></div>${spark(series(m),m.market==='CN'?'var(--teal)':'var(--blue)')}<div class="metric-foot"><span>${r?esc(r.period):'尚未形成数据判断'}</span><span>查看面板 →</span></div></button>`}).join('')}</div>`+
 section('从总量穿透到主体',`<button class="text-btn" data-nav="companies">公司与对照组 →</button>`)+`<div class="card card-pad"><div class="grid-3"><div><div class="eyebrow">融资主体</div><h3>政府 / 企业 / 居民</h3><p class="card-sub">银行与非银、内部现金与债务融资分开。</p></div><div><div class="eyebrow">产业节点</div><h3>上游 / 中游 / 下游</h3><p class="card-sub">核对订单、现金和账期的传导方向。</p></div><div><div class="eyebrow">分配结果</div><h3>头部 / 中位数 / 改善宽度</h3><p class="card-sub">38家候选锚点，统计对照组尚待正式冻结。</p></div></div></div>`;
}
function panelPage(){const p=CFG.panels.find(p=>p.id===state.panel);const mm=CFG.metrics.filter(m=>m.panel===p.id&&visibleMetric(m));return pageHead('OBSERVATION PANEL',p.name,p.question,`<button class="pill" data-nav="overview">← 周期总览</button>`+marketFilter())+`<div class="chain-tabs">${CFG.panels.map(x=>`<button data-panel="${x.id}" class="${x.id===p.id?'active':''}">${x.name}</button>`).join('')}</div><div class="explain">口径边界：${p.caution}</div><div class="grid-3">${mm.map(metricCard).join('')}</div>`+(p.id==='breadth'?distribution():'')+section('沿着传导链继续验证')+`<div class="grid-3">${CFG.chains.filter(c=>c.metrics.some(id=>mm.some(m=>m.id===id))).map(c=>`<button class="card card-pad" style="text-align:left" data-chain="${c.id}"><div class="eyebrow">传导链 ${c.id}</div><h3>${c.name} →</h3><p class="card-sub">${c.question}</p></button>`).join('')}</div>`}
function distribution(){return section('集中与扩散必须一起看')+`<div class="grid-2"><div class="card card-pad"><div class="card-top"><h3>龙头与其他企业的现金流率</h3>${modeBadge()}</div>${state.mode==='demo'?['头部组 · 8家','非头部组 · 24家','全样本中位数'].map((x,i)=>`<div class="distribution-row"><span>${x}</span><div class="bar-track"><div class="bar-fill" style="width:${[76,31,44][i]}%"></div></div><span class="mono">${[22.8,9.3,13.2][i]}%</span></div>`).join(''):empty('对照组尚未冻结','需补齐非头部样本、分组依据和有效财务数据。')}<p class="card-sub">示例仅说明比较方式；候选锚点不能代表全行业。</p></div><div class="card card-pad"><h3>四项同时展示</h3><div class="detail-list" style="margin-top:16px"><dt>总体变化</dt><dd>汇总收入、利润、现金流和投资</dd><dt>典型企业</dt><dd>中位数与上下四分位数</dd><dt>改善宽度</dt><dd>同口径同比改善 / 有效可比企业</dd><dt>头部份额</dt><dd>固定头部组份额和剔除头部后的增长</dd></div></div></div>`}
function chainPage(){const c=CFG.chains.find(c=>c.id===state.chain);return pageHead('TRANSMISSION MAP','从资金来源，追到终端回报','按具体产品和支出关系组织上中下游；公司为候选观察锚点，关联不等于已验证的直接供应关系。')+`<div class="chain-tabs">${CFG.chains.map(x=>`<button data-chain="${x.id}" class="${x.id===c.id?'active':''}">${x.id} · ${x.name}</button>`).join('')}</div><div class="card card-pad"><div class="card-top"><div>${marketBadge(c.market)}<h2 style="margin-top:10px">${c.question}</h2></div><button class="pill" data-note-target="${c.id}">＋ 添加链条证据</button></div><p class="subtitle">资金入口：${c.funding}</p><div class="chain-diagram">${c.nodes.map((n,i)=>`<article class="chain-node"><div class="stage mono">${['UPSTREAM','MIDSTREAM','DOWNSTREAM'][i]}</div><h3>${n[0]}</h3><p>${n[1]}</p></article>`).join('')}</div><div class="grid-2"><div class="hypo"><b>什么会增强这条命题</b>${c.support}</div><div class="hypo counter"><b>什么会削弱这条命题</b>${c.counter}</div></div></div>`+section('宏观与行业验证序列')+`<div class="grid-3">${c.metrics.map(id=>metricCard(metricBy(id))).join('')}</div>`+section('相关公司锚点',`<button class="text-btn" data-company-chain="${c.id}">打开完整观察组 →</button>`)+companyTable(CFG.companies.filter(x=>x.chain===c.id))+section('这条链的研究证据')+notesList(saved.notes.filter(n=>n.target===c.id));}
function mockCompany(c){const h=hash(c.id);return {revenue:((h%210)-40)/10,margin:((h%55)-20)/10,cash:(h%270)/10,interest:1.1+(h%130)/10,capex:60+(h%160)}}
function companyTable(list){return `<div class="card table-wrap"><table class="data-table"><thead><tr><th>公司 / 证券</th><th>上市地</th><th>链条节点</th><th>收入同比</th><th>利润率变化</th><th>经营现金流率</th><th>利息覆盖</th><th>观察状态</th></tr></thead><tbody>${list.map(c=>{const d=state.mode==='demo'?mockCompany(c):{},special=['银行','交易所','地产'].includes(c.sector);return `<tr data-company="${esc(c.id)}" tabindex="0" role="button" aria-label="查看${esc(c.name)}"><td><strong>${esc(c.name)}</strong><span class="secondary mono">${esc(c.id)}</span></td><td>${marketBadge(c.market)}</td><td>${c.chain} · ${c.stage}<span class="secondary">${c.sector}</span></td><td>${num(d.revenue)}</td><td>${num(d.margin,'pp')}</td><td>${special?'<span class="muted">专用口径</span>':num(d.cash)}</td><td>${special?'<span class="muted">专用口径</span>':num(d.interest,'倍')}</td><td><span class="badge ${state.mode==='demo'?'demo':''}">${state.mode==='demo'?'示例':c.anchor?'原始候选':'补充候选'}</span></td></tr>`}).join('')||'<tr><td colspan="8">没有匹配对象，请调整筛选。</td></tr>'}</tbody></table></div>`}
function companyPage(){let list=CFG.companies.filter(c=>(state.market==='ALL'||state.market===c.market)&&(state.companyChain==='ALL'||c.chain===state.companyChain)&&(state.stage==='ALL'||c.stage===state.stage)&&(c.name+' '+c.id).toLowerCase().includes(state.search.toLowerCase()));list.sort((a,b)=>state.sort==='market'?a.market.localeCompare(b.market):state.sort==='revenue'&&state.mode==='demo'?mockCompany(b).revenue-mockCompany(a).revenue:a.name.localeCompare(b.name,'zh'));return pageHead('COMPANY OBSERVATORY','公司与对照组','先检验融资、经营和偿债，再观察市场定价。上市地与业务敞口分开；非龙头和融资资质分组仍待样本冻结。',marketFilter(['ALL','CN','HK','US']))+`<div class="stat-strip"><div><small>候选公司</small><b class="mono">38</b></div><div><small>传导链</small><b class="mono">5</b></div><div><small>已核实公司财务</small><b class="mono">0</b></div><div><small>本次筛选</small><b class="mono">${list.length}</b></div></div><div class="toolbar"><input class="search" id="company-search" type="search" placeholder="搜索公司或证券代码" aria-label="搜索公司" value="${esc(state.search)}"><div class="filters"><select id="company-chain" aria-label="公司传导链"><option value="ALL">全部传导链</option>${CFG.chains.map(c=>`<option value="${c.id}" ${state.companyChain===c.id?'selected':''}>${c.id} · ${c.name}</option>`).join('')}</select><select id="company-stage" aria-label="产业链节点">${['ALL','上游','中游','下游','金融'].map(s=>`<option value="${s}" ${state.stage===s?'selected':''}>${s==='ALL'?'全部节点':s}</option>`).join('')}</select><select id="company-sort" aria-label="排序">${[['name','按公司名称'],['market','按上市地'],...(state.mode==='demo'?[['revenue','收入增速降序 · 示例']]:[])].map(([v,l])=>`<option value="${v}" ${state.sort===v?'selected':''}>${l}</option>`).join('')}</select></div></div>${companyTable(list)}<div class="explain">财务值尚未接通；演示数值仅用于检查比较体验。银行、交易所、开发商采用专用模板。候选公司的链条归属用于研究组织，供应关系、所有制、客户集中度和融资资质需要原始披露验证。</div>`+distribution()}
function marketPage(){const list=CFG.indices.filter(x=>state.market==='ALL'||state.market===x.market),styles=CFG.styles.filter(x=>state.market==='ALL'||state.market===x.market);return pageHead('MARKET REFERENCE','指数与风格参照','市场价格用于验证定价与扩散。三个中国市场层次与日本参照分别展示；供应商代码与收益口径待映射。',marketFilter(['ALL','CN','HK','US','JP']))+`<div class="card table-wrap"><table class="data-table"><thead><tr><th>指数</th><th>市场</th><th>近3个月收益</th><th>近12个月收益</th><th>近24期走势</th><th>数据状态</th></tr></thead><tbody>${list.map(x=>{const rows=state.mode==='demo'?mockSeries(x.id):[];return `<tr><td><strong>${x.name}</strong><span class="secondary mono">${x.id} · 展示标识</span></td><td>${marketBadge(x.market)}</td><td>${num(state.mode==='demo'?hash(x.id)%150/10-4:null)}</td><td>${num(state.mode==='demo'?hash(x.id)%330/10-5:null)}</td><td style="width:200px">${rows.length?spark(rows):'—'}</td><td><span class="badge ${state.mode==='demo'?'demo':''}">${state.mode==='demo'?'示例 · 合成':'行情待接入'}</span></td></tr>`}).join('')}</tbody></table></div>`+section('10组相对表现与结构比较')+`<div class="grid-3">${styles.map(x=>`<article class="card card-pad"><div class="card-top"><h3>${x.name}</h3>${marketBadge(x.market)}</div><p class="card-sub">${x.pair}</p>${spark(state.mode==='demo'?mockSeries(x.pair):[])}<small>${state.mode==='demo'?'示例曲线，非实际相对收益':'同口径总收益优先；待连接历史序列'}</small></article>`).join('')}</div><div class="explain">日本以TOPIX为主基准，日经225作结构比较；港股观察中国资产离岸定价，不等同于整体新兴市场。指数与ETF分开；不得用ETF成交量代表指数整体成交量。</div>`}
function horizonPage(){return pageHead('FORWARD COMMITMENTS','2027—2028：兑现与到期','把已经形成的约束，与尚待验证的经营结果分开记录。年份表示研究窗口，不代表预测数据。')+`<div class="timeline-grid">${[2027,2028].map(y=>`<div class="card year-card"><div class="card-top"><div class="year-title">${y}</div><span class="badge">研究窗口</span></div>${[['到期债务','本金、票息、浮息比例、现金与授信覆盖'],['投资与投产','资本开支承诺、在建工程、投产与折旧'],['订单与回报','交付期限、取消条款、回款及终端需求']].map(([t,d])=>`<div class="commitment"><span class="badge">待核实</span><div><h3>${t}</h3><p>${d}</p></div></div>`).join('')}<p class="card-sub" style="margin-top:15px">已记录 ${saved.commitments.filter(c=>c.year===String(y)).length} 条研究事项</p></div>`).join('')}</div>`+section('登记一个需要验证的未来事项')+`<form id="commit-form" class="card card-pad"><div class="form-grid"><label class="field">主体或链条<input name="entity" required maxlength="100" placeholder="例如：AI客户组 / 某公司"></label><label class="field">事项类型<select name="kind"><option>已披露承诺</option><option>待验证经营结果</option><option>情景假设</option></select></label><label class="field">研究年份<select name="year"><option>2027</option><option>2028</option></select></label><label class="field">原始来源（已披露承诺必填）<input name="url" type="url" placeholder="https://..."></label><label class="field wide">事项与验证条件<textarea name="body" required maxlength="5000" placeholder="记录到期债务、投资承诺或需要看到的经营结果。情景假设明确写出假设条件。"></textarea></label></div><button class="pill primary" type="submit" style="margin-top:15px">保存未来事项</button></form>`+section('已登记事项')+`<div class="card">${saved.commitments.length?saved.commitments.map(c=>`<article class="evidence-item"><div class="note-meta"><strong>${esc(c.year)} · ${esc(c.entity)}</strong><span class="badge">${esc(c.kind)}</span></div><p>${esc(c.body)}</p>${safeUrl(c.url)?`<a target="_blank" rel="noopener noreferrer" href="${esc(safeUrl(c.url))}">查看原始来源 ↗</a>`:''}<div class="line-foot"><small>${esc(c.created.slice(0,10))}</small><button class="text-btn" data-delete-commit="${esc(c.id)}">删除</button></div></article>`).join(''):empty('暂无未来事项','先记录已披露的约束，再补充可证伪的情景。')}</div>`}
function targetOptions(selected='A'){return [...(CFG.narratives||[]).map(n=>[n.id,'叙事 · '+n.name]),...CFG.chains.map(c=>[c.id,`链条 ${c.id} · ${c.name}`]),...CFG.panels.map(p=>[p.id,`面板 · ${p.name}`]),...CFG.companies.map(c=>[c.id,c.name])].map(([v,l])=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(l)}</option>`).join('')}
function noteForm(target='A'){return `<form id="note-form" class="card card-pad"><div class="form-grid"><label class="field">关联对象<select name="target">${targetOptions(target)}</select></label><label class="field">证据方向<select name="direction"><option>待验证</option><option>支持证据</option><option>反向证据</option><option>口径修正</option></select></label><label class="field wide">事实、推断与下一验证条件<textarea name="body" required maxlength="10000" placeholder="建议分开写：已知事实 / 解释与假设 / 下次需要验证什么。"></textarea></label><label class="field wide">来源链接<input name="url" type="url" placeholder="https://..."></label></div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:15px;gap:12px"><small>笔记保存在本浏览器，请定期导出。</small><button class="pill primary" type="submit">保存证据</button></div></form>`}
function targetName(t){return CFG.narratives?.find(n=>n.id===t)?.name|| CFG.chains.find(c=>c.id===t)?.name||CFG.panels.find(p=>p.id===t)?.name||CFG.companies.find(c=>c.id===t)?.name||t}
function notesList(list){return `<div class="card">${list.length?list.map(n=>`<article class="evidence-item"><div class="note-meta"><strong>${esc(targetName(n.target))}</strong><span class="badge">${esc(n.direction)}</span></div><p>${esc(n.body)}</p>${safeUrl(n.url)?`<a href="${esc(safeUrl(n.url))}" target="_blank" rel="noopener noreferrer">查看证据来源 ↗</a>`:''}<div class="line-foot"><small>${esc(n.created.slice(0,16).replace('T',' '))} · ${n.demo?'演示时记录':'研究记录'}</small><button class="text-btn" data-delete-note="${esc(n.id)}">删除</button></div></article>`).join(''):empty('保留每一次判断的依据','记录支持与反向证据，让后续复盘有据可查。')}</div>`}
function evidencePage(){return pageHead('RESEARCH LOG','研究证据与判断记录','证据方向由研究者记录，不由价格涨跌自动决定。保留事实、解释、来源和下一验证条件。')+noteForm(state.noteTarget||'A')+section('已保存的研究记录',`<span class="badge">${saved.notes.length} 条</span>`)+notesList(saved.notes)}
function sourcePage(){return pageHead('DATA & PROVENANCE','数据接入与口径','本地工作台已经可以导入和维护宏观序列；供应商自动同步、公司财务和行情适配仍待接通。')+`<div class="stat-strip"><div><small>已配置宏观序列</small><b class="mono">${CFG.metrics.length}</b></div><div><small>已录入观察值</small><b class="mono">${saved.records.length}</b></div><div><small>自动连接</small><b class="mono">0</b></div><div><small>研究记录与事项</small><b class="mono">${saved.notes.length+saved.commitments.length}</b></div></div><div class="import-area"><h3>接入你的已核实数据</h3><p>下载JSON模板，按指标ID填入数据后导入。相同指标与所属日期以本次导入值更新；不同日期合并。最多20,000条，导入前会完整校验。</p><div class="filters"><button class="pill primary" id="choose-import">导入指标数据</button><button class="pill" id="download-template">下载数据模板</button><button class="pill" id="download-dictionary">下载指标字典</button><button class="pill" id="choose-restore">导入研究备份</button></div><p style="margin-bottom:0">只接受有限数值、有效日期和HTTP(S)来源。历史修订值更新当前视图，旧观察值自动归档并包含在研究备份中。这里不需要填写任何账户密钥。</p></div>`+section('来源登记与接入状态')+`<div class="source-list">${Object.entries(CFG.sources).map(([id,s])=>`<article class="card source-card"><div class="card-top"><h3>${s[0]}</h3><span class="badge">${id==='calc'?'待冻结样本':'未自动连接'}</span></div><p>${s[2]}</p>${s[1]?`<a href="${esc(s[1])}" target="_blank" rel="noopener noreferrer">打开来源入口 ↗</a>`:'<small>以数据与授权可得性确定接入方式</small>'}</article>`).join('')}</div>`+section('指标字典',`<span class="muted" style="font-size:11px">点击一行查看口径，或直接录入观察值</span>`)+`<div class="card table-wrap"><table class="data-table"><thead><tr><th>指标 / ID</th><th>市场</th><th>面板</th><th>频率</th><th>观察值</th><th>来源</th></tr></thead><tbody>${CFG.metrics.map(m=>`<tr data-metric="${m.id}" tabindex="0" role="button"><td>${m.name}<span class="secondary mono">${m.id}</span></td><td>${marketBadge(m.market)}</td><td>${(CFG.panels.find(p=>p.id===m.panel)?.name||'宏观观察')}</td><td>${m.freq}度</td><td>${saved.records.filter(r=>r.metricId===m.id).length}</td><td>${CFG.sources[m.source][0]}</td></tr>`).join('')}</tbody></table></div>`}
function render(){document.getElementById('nav').innerHTML=NAV.map(([id,icon,label])=>`<button data-nav="${id}" class="${state.page===id?'active':''}" ${state.page===id?'aria-current="page"':''}><span class="ico" aria-hidden="true">${icon}</span>${label}</button>`).join('');document.getElementById('crumb').textContent='研究工作台 / '+(NAV.find(n=>n[0]===state.page)?.[2]||'观测面板');document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===state.mode);b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode))});const fn=state.panel&&state.page==='overview'?panelPage:{overview,chains:chainPage,companies:companyPage,markets:marketPage,horizon:horizonPage,evidence:evidencePage,sources:sourcePage}[state.page];document.getElementById('main').innerHTML=notice()+fn()+`<footer class="footer"><span>周期观察台 V0.1 · 已知事实 / 研究假设 / 待验证事项分别保留</span><span>本地工作台 · 不自动运行或发送通知</span></footer>`}
function navigate(p){state.page=p;state.panel=null;state.market='ALL';closeDrawer(false);render();window.scrollTo({top:0,behavior:'instant'})}
function openDrawer(content){if(!document.querySelector('.drawer'))lastFocus=document.activeElement;document.getElementById('drawer-root').innerHTML=`<div class="drawer-overlay"><section class="drawer" role="dialog" aria-modal="true" aria-label="研究详情"><div class="drawer-head"><span class="eyebrow">RESEARCH DETAIL</span><button class="close" id="close-drawer" aria-label="关闭详情">×</button></div>${content}</section></div>`;document.body.style.overflow='hidden';document.querySelector('.drawer .close').focus()}
function closeDrawer(restore=true){document.getElementById('drawer-root').innerHTML='';document.body.style.overflow='';state.drawer=null;if(restore&&lastFocus?.isConnected)lastFocus.focus()}
function openMetric(id){const m=metricBy(id);if(!m)return;const rows=series(m),r=rows.at(-1),src=CFG.sources[m.source];state.drawer={type:'metric',id};openDrawer(`<div class="card-top">${marketBadge(m.market)}${modeBadge()}</div><h2 style="margin-top:12px">${m.name}</h2><p class="subtitle">${m.meaning}</p><div class="metric-row"><div class="big-number">${num(r?.value,m.unit)}</div><span class="badge">${m.freq}度</span></div><div class="toolbar"><span class="muted" style="font-size:11px">${state.mode==='demo'?'合成数据 · 日期非真实发布':'已录入历史'}</span><div class="chart-range">${[6,12,24].map(n=>`<button data-range="${n}" class="${state.range===n?'active':''}">${n}期</button>`).join('')}</div></div><div class="chart-lg">${spark(rows,m.market==='CN'?'var(--teal)':'var(--blue)',true)}</div><h3>定义与证据</h3><dl class="detail-list"><dt>计算口径</dt><dd>${m.formula}</dd><dt>序列ID</dt><dd class="mono">${m.id}</dd><dt>所属时期</dt><dd>${r?esc(r.period):'未录入'}</dd><dt>发布日期</dt><dd>${r?esc(r.publishedAt):'未录入'}</dd><dt>来源</dt><dd>${r?esc(r.sourceLabel):src[0]} ${safeUrl(r?.sourceUrl)?`<a href="${esc(safeUrl(r.sourceUrl))}" target="_blank" rel="noopener noreferrer">原始记录 ↗</a>`:''}</dd><dt>样本数量</dt><dd>${r?.sampleSize??'未提供 / 不适用'}</dd><dt>备注</dt><dd>${r?.notes?esc(r.notes):src[2]}</dd></dl><h3>观察值</h3><div class="table-wrap" style="max-height:220px"><table class="data-table"><thead><tr><th>所属日期</th><th>值 (${m.unit})</th><th>发布日期</th></tr></thead><tbody>${rows.slice().reverse().map(x=>`<tr><td>${esc(x.period)}</td><td class="mono">${fmt(x.value)}</td><td>${esc(x.publishedAt)}</td></tr>`).join('')||'<tr><td colspan="3">尚无数据</td></tr>'}</tbody></table></div>${state.mode==='real'?`<h3>录入一条已核实观察值</h3><form id="record-form"><input type="hidden" name="metricId" value="${id}"><div class="form-grid"><label class="field">所属日期<input name="period" type="date" required></label><label class="field">发布日期<input name="publishedAt" type="date" required></label><label class="field">数值 (${m.unit})<input name="value" type="number" step="any" required></label><label class="field">有效样本数（选填）<input name="sampleSize" type="number" min="0" step="1"></label><label class="field wide">原始来源链接<input name="sourceUrl" type="url" required placeholder="https://..."></label><label class="field wide">口径或修订说明<input name="notes" maxlength="2000" placeholder="累计/当期、季调、样本覆盖等"></label></div><button class="pill primary" type="submit" style="margin-top:14px">保存观察值</button></form>`:'<div class="explain">切换回研究数据模式后，可录入核实后的观察值。</div>'}`)}
function openCompany(id){const c=CFG.companies.find(c=>c.id===id);if(!c)return;state.drawer={type:'company',id};const special=['银行','交易所','地产'].includes(c.sector),fields=special?['贷款 / 资产结构','净息差或专用盈利指标','逾期与信用减值','资本与流动性','2027—2028到期安排','经营披露与现金回收']:['融资来源与偿还额','内部现金覆盖资本开支','2027 / 2028到期债务','利息保障倍数','资本开支与折旧','订单与交付','收入量价拆分','毛利率与利润率','库存周转天数','应收与合同资产','应付及供应链融资','自由现金流与ROIC'];openDrawer(`${marketBadge(c.market)}<h2 style="margin-top:12px">${c.name}</h2><p class="subtitle mono">${c.id} · ${c.sector} · ${c.chain}链 / ${c.stage}</p><div class="explain">候选研究锚点。实际业务敞口、客户关系和财务口径尚待披露核验。${c.id==='TSM'?'台积电以美股ADR为证券入口，经营敞口不能归作美国本土。':''}</div><h3>资金—经营—偿债观测表</h3><div class="table-wrap"><table class="data-table"><tbody>${fields.map(f=>`<tr><td>${f}</td><td class="muted">待接入</td></tr>`).join('')}</tbody></table></div><p class="card-sub">${special?'使用行业专用模板，不能套用一般工业企业自由现金流指标。':'演示列表仅展示部分合成财务字段；此处不生成未经披露的债务或订单。'}</p><h3>2027—2028年验证点</h3><div class="hypo">到期债务、采购与投资承诺、投产折旧、订单取消及终端回报。每条记录区分已披露承诺和情景假设。</div><div class="filters" style="margin:20px 0"><button class="pill primary" data-note-target="${esc(c.id)}">记录公司证据</button><button class="pill" data-chain="${c.chain}">查看传导链</button></div><h3>公司研究记录</h3>${notesList(saved.notes.filter(n=>n.target===id))}`)}
function validDate(x){return typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)&&!isNaN(Date.parse(x))&&new Date(x).toISOString().slice(0,10)===x}
function validateRecords(items){if(!Array.isArray(items)||!items.length||items.length>20000)throw Error('records必须包含1至20,000条观察值。');const seen=new Set();return items.map((r,i)=>{const n=i+1;if(!r||!metricBy(r.metricId))throw Error(`第${n}条：指标ID未在字典中定义。`);if(!validDate(r.period)||!validDate(r.publishedAt))throw Error(`第${n}条：日期需为有效YYYY-MM-DD。`);if(r.publishedAt<r.period)throw Error(`第${n}条：发布日期不能早于所属日期。`);if(typeof r.value!=='number'||!Number.isFinite(r.value))throw Error(`第${n}条：value必须是已核实的有限数值，不能为null或字符串。`);if(!safeUrl(r.sourceUrl))throw Error(`第${n}条：需要HTTP(S)原始来源链接。`);if(typeof r.sourceLabel!=='string'||!r.sourceLabel.trim())throw Error(`第${n}条：需要sourceLabel来源名称。`);if(r.sampleSize!==undefined&&r.sampleSize!==null&&(!Number.isInteger(r.sampleSize)||r.sampleSize<0))throw Error(`第${n}条：样本数需为非负整数。`);const k=r.metricId+'|'+r.period;if(seen.has(k))throw Error(`第${n}条：同批数据存在重复指标与日期。`);seen.add(k);return {metricId:r.metricId,period:r.period,publishedAt:r.publishedAt,value:r.value,sourceUrl:safeUrl(r.sourceUrl),sourceLabel:r.sourceLabel.slice(0,200),sampleSize:r.sampleSize??null,notes:String(r.notes||'').slice(0,5000)}})}
function mergeRecords(records){const map=new Map(saved.records.map(r=>[r.metricId+'|'+r.period,r]));for(const r of records){const k=r.metricId+'|'+r.period,old=map.get(k);if(old&&JSON.stringify(old)!==JSON.stringify(r))saved.revisions.push({...old,archivedAt:new Date().toISOString()});map.set(k,r);}saved.records=[...map.values()];persist()}
function download(name,obj){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function backup(){return {app:'credit-observatory',schemaVersion:1,exportedAt:new Date().toISOString(),records:saved.records,notes:saved.notes,commitments:saved.commitments,revisions:saved.revisions}}
function exportAll(){download('投研观察台-研究备份-'+new Date().toISOString().slice(0,10)+'.json',backup());toast('研究备份已导出。示例数据不包含在备份中。')}
function template(){return {schemaVersion:1,datasetLabel:'填写数据集名称',records:[{metricId:'us_inflation',period:'2026-07-31',publishedAt:'2026-08-28',value:null,sourceUrl:'https://www.bea.gov/data/personal-consumption-expenditures-price-index',sourceLabel:'BEA 原始发布',sampleSize:null,notes:'value及日期请按原始发布核实后填写；当前不是可导入的真实数据。'}]}}
document.addEventListener('click',e=>{
 const b=e.target.closest('button,[data-company],[data-metric]');if(!b){if(e.target.classList.contains('drawer-overlay'))closeDrawer();return}
 if(b.dataset.nav){navigate(b.dataset.nav);return}
 if(b.dataset.mode){state.mode=b.dataset.mode;closeDrawer(false);render();return}
 if(b.dataset.panel){state.page='overview';state.panel=b.dataset.panel;if(!['ALL','CN','US'].includes(state.market))state.market='ALL';closeDrawer(false);render();window.scrollTo(0,0);return}
 if(b.dataset.chain){state.chain=b.dataset.chain;navigate('chains');return}
 if(b.dataset.companyChain){state.companyChain=b.dataset.companyChain;navigate('companies');return}
 if(b.dataset.metric){openMetric(b.dataset.metric);return}
 if(b.dataset.company){openCompany(b.dataset.company);return}
 if(b.dataset.range){const id=state.drawer?.id;state.range=Number(b.dataset.range);if(id)openMetric(id);return}
 if(b.dataset.noteTarget){state.noteTarget=b.dataset.noteTarget;navigate('evidence');return}
 if(b.dataset.deleteNote){if(confirm('删除这条研究记录？此操作会修改本地记录。')){saved.notes=saved.notes.filter(n=>n.id!==b.dataset.deleteNote);persist();closeDrawer(false);render();toast('研究记录已删除。')}return}
 if(b.dataset.deleteCommit){if(confirm('删除这个未来事项？')){saved.commitments=saved.commitments.filter(c=>c.id!==b.dataset.deleteCommit);persist();render();toast('未来事项已删除。')}return}
 switch(b.id){case 'close-drawer':closeDrawer();break;case 'export-all':exportAll();break;case 'choose-import':document.getElementById('import-file').click();break;case 'choose-restore':document.getElementById('restore-file').click();break;case 'download-template':download('data-template.json',template());break;case 'download-dictionary':download('research-config.json',CFG);break}
});
document.addEventListener('change',e=>{const el=e.target;if(el.id==='market-filter'){state.market=el.value;render()}if(el.id==='company-chain'){state.companyChain=el.value;render()}if(el.id==='company-stage'){state.stage=el.value;render()}if(el.id==='company-sort'){state.sort=el.value;render()}});
document.addEventListener('input',e=>{if(e.target.id==='company-search'){const pos=e.target.selectionStart;state.search=e.target.value;render();const f=document.getElementById('company-search');f.focus();f.setSelectionRange(pos,pos)}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer();if(['Enter',' '].includes(e.key)&&e.target.matches('tr[data-company],tr[data-metric]')){e.preventDefault();e.target.click()}if(e.key==='Tab'&&document.querySelector('.drawer')){const nodes=[...document.querySelectorAll('.drawer button,.drawer a,.drawer input,.drawer select,.drawer textarea')].filter(x=>!x.disabled&&!x.hidden),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}});
document.addEventListener('submit',e=>{const f=e.target;if(!['note-form','commit-form','record-form'].includes(f.id))return;e.preventDefault();const d=Object.fromEntries(new FormData(f));try{
 if(f.id==='note-form'){if(!d.body.trim())throw Error('请填写证据内容。');if(d.url&&!safeUrl(d.url))throw Error('来源必须是HTTP(S)链接。');saved.notes.unshift({id:uid(),target:d.target,direction:d.direction,body:d.body.trim(),url:d.url,created:new Date().toISOString(),demo:state.mode==='demo'});persist();render();toast('证据已保存到本浏览器。')}
 if(f.id==='commit-form'){if(!d.body.trim()||!d.entity.trim())throw Error('请填写主体与验证事项。');if((d.kind==='已披露承诺'||d.url)&&!safeUrl(d.url))throw Error('已披露承诺需要HTTP(S)原始来源链接。');saved.commitments.unshift({id:uid(),entity:d.entity.trim(),year:d.year,kind:d.kind,body:d.body.trim(),url:d.url,created:new Date().toISOString()});persist();render();toast('未来事项已保存。')}
 if(f.id==='record-form'){const item={...d,value:d.value===''?null:Number(d.value),sampleSize:d.sampleSize===''?null:Number(d.sampleSize),sourceLabel:CFG.sources[metricBy(d.metricId).source][0]};const records=validateRecords([item]);mergeRecords(records);render();openMetric(d.metricId);toast('观察值已保存。')}
 }catch(err){toast(err.message)}});
document.getElementById('import-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('文件超过10MB，请拆分后导入。');const data=JSON.parse(await file.text());if(data.schemaVersion!==1)throw Error('不支持的数据版本，需要schemaVersion: 1。');const rows=validateRecords(data.records);mergeRecords(rows);state.mode='real';render();toast(`已合并${rows.length}条观察值。`)}catch(err){toast('未导入：'+err.message)}e.target.value=''});
document.getElementById('restore-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('备份超过10MB。');const data=JSON.parse(await file.text());if(data.app!=='credit-observatory'||data.schemaVersion!==1||!Array.isArray(data.notes)||!Array.isArray(data.commitments)||!Array.isArray(data.records))throw Error('不是有效的研究备份。');const extra=validateExtendedBackup(data);const records=data.records.length?validateRecords(data.records):[];if(data.revisions!==undefined&&!Array.isArray(data.revisions))throw Error('修订记录格式无效。');const revisions=(data.revisions||[]).map(x=>{const r=validateRecords([x])[0];if(typeof x.archivedAt!=='string'||isNaN(Date.parse(x.archivedAt)))throw Error('修订时间无效。');return {...r,archivedAt:x.archivedAt}});for(const n of data.notes)if(!n||typeof n.id!=='string'||typeof n.target!=='string'||typeof n.direction!=='string'||typeof n.body!=='string'||typeof n.created!=='string'||isNaN(Date.parse(n.created))||(n.url&&!safeUrl(n.url)))throw Error('备份中的研究记录格式无效。');for(const c of data.commitments)if(!c||typeof c.id!=='string'||typeof c.entity!=='string'||typeof c.body!=='string'||!['2027','2028'].includes(c.year)||typeof c.created!=='string'||isNaN(Date.parse(c.created))||!['已披露承诺','待验证经营结果','情景假设'].includes(c.kind)||((c.kind==='已披露承诺'||c.url)&&!safeUrl(c.url)))throw Error('备份中的未来事项格式无效。');if(!confirm(`合并${records.length}条观察值、${data.notes.length}条证据、${data.commitments.length}个未来事项？同ID记录以本次备份为准，观察值旧版本自动归档。`))return;const notes=new Map(saved.notes.map(x=>[x.id,x])),cc=new Map(saved.commitments.map(x=>[x.id,x]));data.notes.forEach(x=>notes.set(x.id,x));data.commitments.forEach(x=>cc.set(x.id,x));saved.notes=[...notes.values()];saved.commitments=[...cc.values()];mergeExtendedBackup(extra);saved.revisions=[...new Map([...saved.revisions,...revisions].map(x=>[JSON.stringify(x),x])).values()];if(records.length)mergeRecords(records);else persist();state.mode='real';render();toast('备份已合并。')}catch(err){toast('未导入：'+err.message)}e.target.value=''});
