export const factorExperimentContract = {
  schemaVersion: 1,
  apiVersion: 'v1',
  module: 'factors',
  status: 'contract_only',
  goal: '在迁入因子实验室前，先固定实验快照、口径、比较限制和结果artifact，避免不同回测口径混用。',
  snapshotRecord: {
    required: [
      'snapshotId',
      'datasetId',
      'asOfDate',
      'universe',
      'frequency',
      'periodStart',
      'periodEnd',
      'sourceIds',
      'hash',
      'createdAt',
    ],
    notes: 'snapshot只描述输入数据版本；不等于实验结论。缺失值、复权、停牌、成分调整和幸存者偏差必须显式记录。',
  },
  factorDefinitionRecord: {
    required: [
      'factorId',
      'name',
      'category',
      'formula',
      'direction',
      'rebalanceRule',
      'neutralization',
      'winsorization',
      'missingValuePolicy',
      'version',
    ],
    categories: ['value', 'quality', 'momentum', 'growth', 'sentiment', 'macro', 'custom'],
    notes: 'factor definition是可复现实验的口径，不承诺有效性；方向和处理规则变更必须升版本。',
  },
  factorLibraryRecord: {
    required: [
      'factorFamilyId',
      'module',
      'title',
      'universe',
      'category',
      'frequency',
      'sourceAssetIds',
      'snapshotIds',
      'fields',
      'status',
      'version',
    ],
    fieldRequired: ['field', 'name', 'role', 'formula', 'direction', 'missingValuePolicy', 'status'],
    statuses: ['candidate', 'mapped_from_source', 'ready_for_experiment', 'deprecated'],
    notes: '常用因子库先登记字段与口径，供后续实验和回测选择；不在登记阶段计算因子值。',
  },
  experimentRecord: {
    required: [
      'experimentId',
      'snapshotId',
      'factorIds',
      'benchmarkId',
      'portfolioRule',
      'rebalanceCalendar',
      'costModel',
      'constraints',
      'comparisonLimits',
      'status',
      'createdAt',
      'resultArtifactId',
    ],
    statuses: ['draft', 'queued', 'running', 'reviewed', 'failed', 'archived'],
    notes: 'experiment只比较同一快照和同一成本/调仓规则下的结果；跨市场、跨频率或不同数据供应商默认不可直接比较。',
  },
  resultArtifactRecord: {
    required: [
      'artifactId',
      'module',
      'experimentId',
      'title',
      'version',
      'createdAt',
      'sourceIds',
      'status',
      'storageRef',
      'metrics',
      'warnings',
    ],
    metrics: ['annualizedReturn', 'maxDrawdown', 'volatility', 'sharpe', 'turnover', 'hitRate', 'informationCoefficient'],
    warnings: ['small_sample', 'lookahead_risk', 'survivorship_risk', 'liquidity_risk', 'regime_dependency'],
    notes: 'result artifact可以被观察台、研究生产和组合复盘引用，但不能自动转化为交易建议。',
  },
  artifactCandidateRecord: {
    required: [
      'artifactCandidateId',
      'module',
      'title',
      'artifactType',
      'sourceProject',
      'sourceScript',
      'inputSnapshotIds',
      'outputRefs',
      'status',
      'migrationPhase',
      'computePolicy',
    ],
    artifactTypes: ['backtest_engine', 'panel_export', 'lab_export', 'factor_study', 'loo_diagnostic', 'sensitivity_grid', 'report_export', 'frontend_demo'],
    statuses: ['mapped_only', 'ready_to_port', 'needs_review', 'deprecated'],
    notes: 'artifact candidate只登记旧项目的实验/导出能力和预期产物；不代表已经在新工作台中执行或复现。',
  },
  dataAssetRecord: {
    required: [
      'assetId',
      'module',
      'title',
      'assetType',
      'storageRef',
      'refreshMode',
      'ownerProject',
      'asOfDate',
      'hashPolicy',
      'notes',
    ],
    assetTypes: ['wide_table', 'sqlite_store', 'parquet_panel', 'update_script', 'source_script'],
    refreshModes: ['manual', 'monthly_incremental', 'quarterly_full', 'derived_offline'],
    notes: '因子实验优先读取现成宽表和面板；只有月度/季度更新时才触发旧抓取链。大数据文件先登记路径和指纹，不复制正文。',
  },
  updateJobRecord: {
    required: ['jobId', 'module', 'command', 'frequency', 'workingDirectory', 'inputs', 'outputs', 'networkPolicy', 'status'],
    statuses: ['documented', 'ready_manual', 'scheduled', 'paused', 'failed'],
    notes: '更新任务必须和回测任务分离；回测默认读取既有数据资产，不隐式抓取。',
  },
  comparisonLimits: [
    '不同snapshotId不可直接比较，除非声明桥接方法。',
    '不同benchmarkId、costModel或rebalanceCalendar不可放入同一排序表。',
    '单因子、组合因子和人工筛选池必须分开展示。',
    '样本数量不足、成交流动性不足或缺失值过多时，结果只能作为诊断。',
    '实盘、纸面组合和历史回测的状态必须分开。',
  ],
};

export const factorDataAssets = [
  { assetId: 'factors.fund_warehouse.nav_db', module: 'factors', title: '基金历史净值 SQLite（新工作台）', assetType: 'sqlite_store',
    storageRef: '/Users/samshi/Desktop/my codex/投研工作台01/var/factors/fund-history.sqlite', refreshMode: 'manual',
    ownerProject: '/Users/samshi/Desktop/my codex/投研工作台01', asOfDate: null, hashPolicy: 'selected_import_source_sha_in_read_transaction',
    notes: '独立离线导入既有名录/净值/基准，记录源SHA和导入异常；查询与回测只读数据库。不是最新基金宽表，也不是外部备份。' },
  ...[['nav_history', '原始基金份额净值目录', 'nav'], ['nav_benchmarks', '基金历史基准指数目录', 'bench'], ['nav_universe', '基金份额名录', 'universe_master.csv']].map(([key, title, file]) => ({
    assetId: `factors.fund_warehouse.${key}`, module: 'factors', title,
    assetType: key === 'nav_universe' ? 'csv_metadata' : 'csv_directory', storageRef: `/Users/samshi/Projects/fund-warehouse/raw/${file}`,
    refreshMode: 'manual', ownerProject: '/Users/samshi/Projects/fund-warehouse', asOfDate: null,
    hashPolicy: 'source_content_sha_on_explicit_offline_import', notes: '旧项目只读导入来源，运行时不再从CSV取净值；无隐式抓取或更新，不把最新宽表用于历史选基。',
  })),
  ...[
    ['basis', '基差原始数据', 'basis.parquet'],
    ['macro_pmi', '制造业PMI月度原始数据', 'macro_pmi.parquet'],
    ['macro_m2', 'M2月度原始数据', 'macro_m2.parquet'],
    ['macro_shibor', 'Shibor每日原始数据', 'macro_shibor.parquet'],
  ].map(([key, title, file]) => ({
    assetId: `factors.etf_smartbeta.${key}`, module: 'factors', title,
    assetType: 'parquet_panel', storageRef: `/Users/samshi/Desktop/My Claude/etf-smartbeta/data/${file}`,
    refreshMode: 'manual', ownerProject: '/Users/samshi/Desktop/My Claude/etf-smartbeta', asOfDate: null,
    hashPolicy: 'stat_only_until_ingested', notes: '三档择时只读输入；模型可用日期不证明历史披露日期，更新脚本不自动执行。',
  })),
  {
    assetId: 'factors.fund_warehouse.wide_today',
    module: 'factors',
    title: '基金截面宽表 wide_today.csv',
    assetType: 'wide_table',
    storageRef: '/Users/samshi/Projects/fund-warehouse/wide_today.csv',
    refreshMode: 'monthly_incremental',
    ownerProject: '/Users/samshi/Projects/fund-warehouse',
    asOfDate: null,
    hashPolicy: 'stat_only_until_ingested',
    notes: '月度更新后的基金截面宽表；回测和筛选优先读取该现成宽表，不每次重新抓取历史。',
  },
  {
    assetId: 'factors.fund_warehouse.fof_db',
    module: 'factors',
    title: '基金宽表 SQLite fof.db',
    assetType: 'sqlite_store',
    storageRef: '/Users/samshi/Projects/fund-warehouse/fof.db',
    refreshMode: 'monthly_incremental',
    ownerProject: '/Users/samshi/Projects/fund-warehouse',
    asOfDate: null,
    hashPolicy: 'stat_only_until_ingested',
    notes: '包含wide_today及相关视图，适合后续本地查询和筛选。',
  },
  {
    assetId: 'factors.fund_warehouse.monthly_update',
    module: 'factors',
    title: '基金数据月度/季度更新脚本',
    assetType: 'update_script',
    storageRef: '/Users/samshi/Projects/fund-warehouse/07_update.sh',
    refreshMode: 'monthly_incremental',
    ownerProject: '/Users/samshi/Projects/fund-warehouse',
    asOfDate: null,
    hashPolicy: 'full_file_hash',
    notes: '月度跑名录、净值增量、基准和宽表；季度额外跑持仓和费率。当前仅登记，不自动执行。',
  },
  {
    assetId: 'factors.fund_warehouse.wide_builder',
    module: 'factors',
    title: '基金宽表生成脚本 05_wide.py',
    assetType: 'source_script',
    storageRef: '/Users/samshi/Projects/fund-warehouse/05_wide.py',
    refreshMode: 'derived_offline',
    ownerProject: '/Users/samshi/Projects/fund-warehouse',
    asOfDate: null,
    hashPolicy: 'full_file_hash',
    notes: '不联网，将01-04产出合成wide_today.csv和fof.db。',
  },
  {
    assetId: 'factors.etf_smartbeta.panel',
    module: 'factors',
    title: 'ETF/行业因子长表 panel.parquet',
    assetType: 'parquet_panel',
    storageRef: '/Users/samshi/Desktop/My Claude/etf-smartbeta/data/panel.parquet',
    refreshMode: 'manual',
    ownerProject: '/Users/samshi/Desktop/My Claude/etf-smartbeta',
    asOfDate: null,
    hashPolicy: 'stat_only_until_ingested',
    notes: '行业因子回测面板；后续迁入因子实验室时作为snapshot候选。',
  },
  {
    assetId: 'factors.etf_smartbeta.broad',
    module: 'factors',
    title: '宽基数据 broad.parquet',
    assetType: 'parquet_panel',
    storageRef: '/Users/samshi/Desktop/My Claude/etf-smartbeta/data/broad.parquet',
    refreshMode: 'manual',
    ownerProject: '/Users/samshi/Desktop/My Claude/etf-smartbeta',
    asOfDate: null,
    hashPolicy: 'stat_only_until_ingested',
    notes: '宽基回测数据；与panel快照分开登记，避免不同口径混排。',
  },
  {
    assetId: 'factors.etf_smartbeta.investable',
    module: 'factors',
    title: '行业ETF可投资起点 investable.parquet',
    assetType: 'parquet_panel',
    storageRef: '/Users/samshi/Desktop/My Claude/etf-smartbeta/data/investable.parquet',
    refreshMode: 'manual',
    ownerProject: '/Users/samshi/Desktop/My Claude/etf-smartbeta',
    asOfDate: null,
    hashPolicy: 'stat_only_until_ingested',
    notes: '按行业名称映射最早ETF可投资日期；仅为行业指数代理的可投资过滤，不证明真实ETF成交或历史成分无偏。',
  },
  {
    assetId: 'factors.etf_smartbeta.bench',
    module: 'factors',
    title: '基准数据 bench.parquet',
    assetType: 'parquet_panel',
    storageRef: '/Users/samshi/Desktop/My Claude/etf-smartbeta/data/bench.parquet',
    refreshMode: 'manual',
    ownerProject: '/Users/samshi/Desktop/My Claude/etf-smartbeta',
    asOfDate: null,
    hashPolicy: 'stat_only_until_ingested',
    notes: '回测基准数据；作为experiment benchmark候选。',
  },
];

export const factorSnapshotCandidates = [
  {
    snapshotId: 'snapshot.fund_warehouse.nav_db.current', datasetId: 'factors.fund_warehouse.nav_db',
    title: '手动基金篮子历史净值（数据库导入版本绑定）', asOfDate: null, universe: 'manual_fund_share_basket',
    frequency: 'daily_observed_nav', periodStart: null, periodEnd: null, sourceIds: [], hash: 'selected_import_source_sha_on_profile', createdAt: null,
    comparisonGroup: 'manual_fund_nav_cashflow_backtest', assetIds: ['factors.fund_warehouse.nav_db'],
    limitations: ['manual_selection_survivorship', 'no_historical_factor_rotation', 'no_dynamic_frozen_bundle', 'adjusted_nav_not_actual_trade_settlement'],
    notes: '执行在数据库读事务中绑定选定份额、单指数与名录的导入SHA，重新导入变化后要求重读保存；不是不可变历史冻结副本。',
  },
  {
    snapshotId: 'snapshot.etf_smartbeta.three_bucket_execution.current', datasetId: 'factors.etf_smartbeta.broad',
    title: 'A/B/C三档执行数据包（八文件）', asOfDate: null, universe: 'broad_index_or_industry_proxy',
    frequency: 'daily_panel_monthly_rebalance', periodStart: null, periodEnd: null, sourceIds: [],
    hash: 'stat_only_until_ingested', createdAt: null, comparisonGroup: 'three_bucket_cashflow_backtest',
    assetIds: ['factors.etf_smartbeta.broad', 'factors.etf_smartbeta.bench', 'factors.etf_smartbeta.panel', 'factors.etf_smartbeta.investable', 'factors.etf_smartbeta.basis', 'factors.etf_smartbeta.macro_pmi', 'factors.etf_smartbeta.macro_m2', 'factors.etf_smartbeta.macro_shibor'],
    limitations: ['industry_index_proxy_not_etf_execution', 'macro_vintages_and_release_dates_unverified', 'synthetic_bond_cash_rate_not_real_bond'],
    notes: '显式三档策略输入，独立于旧宽基/行业快照；冻结必须包含全部八文件。',
  },
  {
    snapshotId: 'snapshot.etf_smartbeta.industry_execution.current',
    datasetId: 'factors.etf_smartbeta.panel',
    title: '原始行业回测数据包（含可投资名单）',
    asOfDate: null,
    universe: 'sw_industry_and_etf_proxy',
    frequency: 'daily_panel_monthly_rebalance',
    periodStart: null,
    periodEnd: null,
    sourceIds: [],
    hash: 'stat_only_until_ingested',
    createdAt: null,
    assetIds: ['factors.etf_smartbeta.panel', 'factors.etf_smartbeta.bench', 'factors.etf_smartbeta.investable'],
    comparisonGroup: 'industry_factor_backtest',
    limitations: ['industry_index_proxy_not_etf_execution', 'historical_universe_and_disclosure_dates_unverified', 'benchmark_hs300_only'],
    notes: '独立于旧panel导出快照；新原始行业执行器读取这三个文件，冻结时完整复制。',
  },
  {
    snapshotId: 'snapshot.fund_warehouse.wide_today.current',
    datasetId: 'factors.fund_warehouse.wide_today',
    title: '基金截面宽表当前快照',
    asOfDate: null,
    universe: 'public_funds',
    frequency: 'monthly_refresh',
    periodStart: null,
    periodEnd: null,
    sourceIds: [],
    hash: 'stat_only_until_ingested',
    createdAt: null,
    assetIds: ['factors.fund_warehouse.wide_today', 'factors.fund_warehouse.fof_db'],
    comparisonGroup: 'fund_cross_section',
    limitations: ['fund_share_and_fund_level_mixed', 'latest_cross_section_only', 'holdings_and_fees_update_quarterly'],
    notes: '用于选基筛选和基金横截面诊断；不与ETF行业回测面板直接比较。',
  },
  {
    snapshotId: 'snapshot.etf_smartbeta.industry_panel.current',
    datasetId: 'factors.etf_smartbeta.panel',
    title: 'ETF/行业因子长表当前快照',
    asOfDate: null,
    universe: 'sw_industry_and_etf_proxy',
    frequency: 'daily_panel_monthly_rebalance',
    periodStart: null,
    periodEnd: null,
    sourceIds: [],
    hash: 'stat_only_until_ingested',
    createdAt: null,
    assetIds: ['factors.etf_smartbeta.panel', 'factors.etf_smartbeta.bench'],
    comparisonGroup: 'industry_factor_backtest',
    limitations: ['industry_index_level', 'etf_only_for_investability_check', 'benchmark_required'],
    notes: '用于行业因子回测候选；回测前必须绑定benchmark、成本和调仓规则。',
  },
  {
    snapshotId: 'snapshot.etf_smartbeta.broad_panel.current',
    datasetId: 'factors.etf_smartbeta.broad',
    title: '宽基因子面板当前快照',
    asOfDate: null,
    universe: 'broad_index',
    frequency: 'daily_panel_monthly_rebalance',
    periodStart: null,
    periodEnd: null,
    sourceIds: [],
    hash: 'stat_only_until_ingested',
    createdAt: null,
    assetIds: ['factors.etf_smartbeta.broad', 'factors.etf_smartbeta.bench'],
    comparisonGroup: 'broad_index_factor_backtest',
    limitations: ['broad_index_only', 'do_not_mix_with_fund_cross_section', 'benchmark_required'],
    notes: '用于宽基策略候选；不与基金宽表或行业面板混排。',
  },
];

export const factorDefinitionCandidates = [
  {
    factorId: 'factor.value',
    name: '价值',
    category: 'value',
    kind: 'smart_beta',
    rule: 1.0,
    formula: 'BM、EP、PB历史分位反向、PE历史分位反向按45/20/25/10合成',
    direction: 'higher_is_better',
    rebalanceRule: 'monthly_cross_section',
    neutralization: 'industry_cross_section_zscore',
    winsorization: 'source_project_default',
    missingValuePolicy: 'source_project_default',
    version: 'source-registry-v1',
    sourceRef: '/Users/samshi/Desktop/My Claude/etf-smartbeta/src/factor_registry.py',
    slots: [
      { slot: 'value.f_bm', column: 'f_bm', name: 'BM 账面市值比', formula: '1 / PB', weight: 0.45, sign: 1 },
      { slot: 'value.f_ep', column: 'f_ep', name: 'EP 盈利收益率', formula: '1 / PE', weight: 0.20, sign: 1 },
      { slot: 'value.f_pbpct', column: 'f_pbpct', name: 'PB 历史分位（反）', formula: '1 - pct(PB | 5y)', weight: 0.25, sign: 1 },
      { slot: 'value.f_pepct', column: 'f_pepct', name: 'PE 历史分位（反）', formula: '1 - pct(PE | 5y)', weight: 0.10, sign: 1 },
    ],
    risks: ['long_underperformance', 'accounting_sensitivity', 'capacity_trap'],
  },
  {
    factorId: 'factor.momentum',
    name: '动量',
    category: 'momentum',
    kind: 'smart_beta',
    rule: 1.0,
    formula: '12-1与6-1两个窗口按65/35合成',
    direction: 'higher_is_better',
    rebalanceRule: 'monthly_cross_section',
    neutralization: 'industry_cross_section_zscore',
    winsorization: 'source_project_default',
    missingValuePolicy: 'source_project_default',
    version: 'source-registry-v1',
    sourceRef: '/Users/samshi/Desktop/My Claude/etf-smartbeta/src/factor_registry.py',
    slots: [
      { slot: 'mom.f_mom12', column: 'f_mom12', name: '12-1 动量', formula: 'P(t-21) / P(t-273) - 1', weight: 0.65, sign: 1 },
      { slot: 'mom.f_mom6', column: 'f_mom6', name: '6-1 动量', formula: 'P(t-21) / P(t-147) - 1', weight: 0.35, sign: 1 },
    ],
    risks: ['momentum_crash', 'high_turnover', 'cost_sensitive'],
  },
  {
    factorId: 'factor.prosperity',
    name: '景气度',
    category: 'growth',
    kind: 'alpha',
    rule: 0.55,
    formula: '盈利同比、环比动能、加速度、BPS增长按40/25/20/15合成',
    direction: 'higher_is_better',
    rebalanceRule: 'monthly_cross_section',
    neutralization: 'industry_cross_section_zscore',
    winsorization: 'source_project_default',
    missingValuePolicy: 'source_project_default',
    version: 'source-registry-v1',
    sourceRef: '/Users/samshi/Desktop/My Claude/etf-smartbeta/src/factor_registry.py',
    slots: [
      { slot: 'prosper.f_eg', column: 'f_eg', name: '盈利同比增速', formula: 'EPS(t) / EPS(t-252) - 1', weight: 0.40, sign: 1 },
      { slot: 'prosper.f_egq', column: 'f_egq', name: '盈利环比动能', formula: 'EPS(t) / EPS(t-63) - 1', weight: 0.25, sign: 1 },
      { slot: 'prosper.f_eacc', column: 'f_eacc', name: '盈利加速度', formula: 'delta(同比增速)', weight: 0.20, sign: 1 },
      { slot: 'prosper.f_bps', column: 'f_bps', name: '每股净资产增长', formula: 'BPS(t) / BPS(t-252) - 1', weight: 0.15, sign: 1 },
    ],
    risks: ['derived_eps_noise', 'reporting_lag', 'lookahead_risk_if_not_shifted'],
  },
  {
    factorId: 'factor.crowding',
    name: '拥挤度惩罚',
    category: 'sentiment',
    kind: 'alpha',
    rule: 0.35,
    formula: '换手、成交额占比、估值扩张、动量二阶按35/25/25/15合成后作为惩罚项',
    direction: 'lower_is_better',
    rebalanceRule: 'monthly_cross_section',
    neutralization: 'industry_cross_section_zscore',
    winsorization: 'source_project_default',
    missingValuePolicy: 'source_project_default',
    version: 'source-registry-v1',
    sourceRef: '/Users/samshi/Desktop/My Claude/etf-smartbeta/src/factor_registry.py',
    slots: [
      { slot: 'crowd.f_turn', column: 'f_turn', name: '换手率分位', formula: 'pct(换手率 | 3y)', weight: 0.35, sign: -1 },
      { slot: 'crowd.f_amt', column: 'f_amt', name: '成交额占比分位', formula: 'pct(成交额/全市场 | 3y)', weight: 0.25, sign: -1 },
      { slot: 'crowd.f_expand', column: 'f_expand', name: '估值扩张', formula: 'PB(t) / PB(t-252) - 1', weight: 0.25, sign: -1 },
      { slot: 'crowd.f_accel', column: 'f_accel', name: '动量二阶', formula: 'delta(12-1 动量)', weight: 0.15, sign: -1 },
    ],
    risks: ['researcher_degrees_of_freedom', 'turnover_sensitive', 'weight_calibration_uncertain'],
  },
];

export const factorTimingDefinitions = [
  {
    timingId: 'timing.pe_decile_gate',
    name: 'PE 十年分位闸门',
    kind: 'beta',
    formula: 'rank(PE_t | 近十年) > threshold 时当月停投',
    notes: '只调仓位，不产生横截面因子暴露。',
  },
  {
    timingId: 'timing.if_basis_percentile',
    name: 'IF 基差分位',
    kind: 'alpha',
    formula: '(IF主力 - 现货) / 现货，取历史分位',
    notes: '市场微观结构与情绪信号；2017-01起才有数据。',
  },
  {
    timingId: 'timing.macro_pmi_m2_shibor',
    name: '宏观 PMI / M2 / Shibor',
    kind: 'beta',
    formula: '权益仓位 = f(PMI, M2同比, Shibor)，各指标按发布滞后右移',
    notes: '右移用于避免前视偏差。',
  },
];

export const factorArtifactCandidates = [
  {
    artifactCandidateId: 'artifact.factor.backtest.monthly_dca_engine',
    module: 'factors',
    title: '三档月度定投回测引擎',
    artifactType: 'backtest_engine',
    sourceProject: '/Users/samshi/Desktop/My Claude/etf-smartbeta',
    sourceScript: '/Users/samshi/Desktop/My Claude/etf-smartbeta/src/backtest.py',
    inputSnapshotIds: ['snapshot.etf_smartbeta.industry_panel.current', 'snapshot.etf_smartbeta.broad_panel.current'],
    outputRefs: ['/Users/samshi/Desktop/My Claude/etf-smartbeta/out'],
    status: 'mapped_only',
    migrationPhase: 'copy_contract_then_port_engine',
    computePolicy: 'manual_only_not_executed',
    notes: '旧项目核心回测引擎；同时报告IRR和TWR，后续迁入前需先固定成本、调仓日历、现金流和benchmark口径。',
  },
  {
    artifactCandidateId: 'artifact.factor.panel.monthly_factor_payload',
    module: 'factors',
    title: '月度因子面板导出',
    artifactType: 'panel_export',
    sourceProject: '/Users/samshi/Desktop/My Claude/etf-smartbeta',
    sourceScript: '/Users/samshi/Desktop/My Claude/etf-smartbeta/src/export_panel.py',
    inputSnapshotIds: ['snapshot.etf_smartbeta.industry_panel.current', 'snapshot.etf_smartbeta.broad_panel.current'],
    outputRefs: ['/Users/samshi/Desktop/My Claude/etf-smartbeta/out/panel.json'],
    status: 'mapped_only',
    migrationPhase: 'port_as_factor_snapshot_export',
    computePolicy: 'manual_only_not_executed',
    notes: '面向前端自建因子策略的月度子因子z-score、可投状态和下月收益payload；后续可作为浏览器端回测输入。',
  },
  {
    artifactCandidateId: 'artifact.factor.lab.configurable_components',
    module: 'factors',
    title: '可配置实验室组件序列导出',
    artifactType: 'lab_export',
    sourceProject: '/Users/samshi/Desktop/My Claude/etf-smartbeta',
    sourceScript: '/Users/samshi/Desktop/My Claude/etf-smartbeta/src/export_lab.py',
    inputSnapshotIds: ['snapshot.etf_smartbeta.industry_panel.current', 'snapshot.etf_smartbeta.broad_panel.current'],
    outputRefs: ['/Users/samshi/Desktop/My Claude/etf-smartbeta/out/lab.json'],
    status: 'mapped_only',
    migrationPhase: 'port_after_factor_library',
    computePolicy: 'manual_only_not_executed',
    notes: '把A/B/C三档拆成可组合单位净值和离散B档因子变体；适合后续新工作台实验配置面板。',
  },
  {
    artifactCandidateId: 'artifact.factor.app.strategy_series',
    module: 'factors',
    title: '交互式演示页序列导出',
    artifactType: 'frontend_demo',
    sourceProject: '/Users/samshi/Desktop/My Claude/etf-smartbeta',
    sourceScript: '/Users/samshi/Desktop/My Claude/etf-smartbeta/src/export_app.py',
    inputSnapshotIds: ['snapshot.etf_smartbeta.industry_panel.current', 'snapshot.etf_smartbeta.broad_panel.current'],
    outputRefs: ['/Users/samshi/Desktop/My Claude/etf-smartbeta/out/app.json'],
    status: 'mapped_only',
    migrationPhase: 'replace_old_page_with_native_module',
    computePolicy: 'manual_only_not_executed',
    notes: '旧演示页需要的策略、基准、买入/停投时点等序列；新工作台应原生重做，不嵌套旧HTML。',
  },
  {
    artifactCandidateId: 'artifact.factor.study.decomposition',
    module: 'factors',
    title: '因子拆解与权重扰动研究',
    artifactType: 'factor_study',
    sourceProject: '/Users/samshi/Desktop/My Claude/etf-smartbeta',
    sourceScript: '/Users/samshi/Desktop/My Claude/etf-smartbeta/src/factor_study.py',
    inputSnapshotIds: ['snapshot.etf_smartbeta.industry_panel.current'],
    outputRefs: ['/Users/samshi/Desktop/My Claude/etf-smartbeta/out/factor_study.json'],
    status: 'mapped_only',
    migrationPhase: 'port_as_experiment_template',
    computePolicy: 'manual_only_not_executed',
    notes: '用于区分smart beta、alpha和权重扰动稳健性；后续应变成可复现实验模板。',
  },
  {
    artifactCandidateId: 'artifact.factor.diagnostic.leave_one_out',
    module: 'factors',
    title: '逐因子与留一法诊断',
    artifactType: 'loo_diagnostic',
    sourceProject: '/Users/samshi/Desktop/My Claude/etf-smartbeta',
    sourceScript: '/Users/samshi/Desktop/My Claude/etf-smartbeta/src/factor_loo.py',
    inputSnapshotIds: ['snapshot.etf_smartbeta.industry_panel.current'],
    outputRefs: ['/Users/samshi/Desktop/My Claude/etf-smartbeta/out/factor_loo.json'],
    status: 'mapped_only',
    migrationPhase: 'port_as_factor_diagnostic',
    computePolicy: 'manual_only_not_executed',
    notes: '逐因子单独使用、留一法边际贡献和换手诊断；新增因子后应自动跟随因子库定义。',
  },
  {
    artifactCandidateId: 'artifact.factor.sensitivity.strategy_knobs',
    module: 'factors',
    title: '策略旋钮敏感性网格',
    artifactType: 'sensitivity_grid',
    sourceProject: '/Users/samshi/Desktop/My Claude/etf-smartbeta',
    sourceScript: '/Users/samshi/Desktop/My Claude/etf-smartbeta/src/sensitivity.py',
    inputSnapshotIds: ['snapshot.etf_smartbeta.industry_panel.current', 'snapshot.etf_smartbeta.broad_panel.current'],
    outputRefs: ['/Users/samshi/Desktop/My Claude/etf-smartbeta/out/sensitivity.parquet'],
    status: 'mapped_only',
    migrationPhase: 'port_as_parameter_sweep',
    computePolicy: 'manual_only_not_executed',
    notes: '定位A/B/C权重、闸门、宽基选择、持仓数量等旋钮的边际影响；不应与单因子有效性混作一个结论。',
  },
  {
    artifactCandidateId: 'artifact.factor.report.performance_pack',
    module: 'factors',
    title: '绩效指标与报告导出',
    artifactType: 'report_export',
    sourceProject: '/Users/samshi/Desktop/My Claude/etf-smartbeta',
    sourceScript: '/Users/samshi/Desktop/My Claude/etf-smartbeta/src/report.py',
    inputSnapshotIds: ['snapshot.etf_smartbeta.industry_panel.current', 'snapshot.etf_smartbeta.broad_panel.current'],
    outputRefs: ['/Users/samshi/Desktop/My Claude/etf-smartbeta/out'],
    status: 'mapped_only',
    migrationPhase: 'port_metrics_before_ui',
    computePolicy: 'manual_only_not_executed',
    notes: '报告侧绩效指标、年度表和归因函数；迁入时要保留IRR/TWR双口径和同基准比较约束。',
  },
];

export const factorLabCapabilityMap = [
  {
    capabilityId: 'lab.factor_definition_inventory',
    title: '因子定义与使用记录列表库',
    requirementRef: '1',
    status: 'native_shell_ready',
    inputRefs: ['factorLibraryRecord', 'experimentRecord', 'artifactCandidateRecord'],
    configFields: ['factorFamilyId', 'fields', 'usageLogic', 'factorFamilyIds', 'strategyTemplateId'],
    outputViews: ['因子定义清单', '子因子/指标清单', '实验配置引用', '策略工具引用'],
    logicNotes: '每个因子族必须能追溯到字段定义、字段公式、方向、缺失值策略、适用snapshot和使用过它的实验配置。',
  },
  {
    capabilityId: 'lab.strategy_config_workbench',
    title: '策略配置工作台',
    requirementRef: '2.1',
    status: 'native_shell_ready',
    inputRefs: ['snapshotRecord', 'factorLibraryRecord', 'experimentRecord'],
    configFields: ['strategyType', 'targetUniverse', 'factorFamilyIds', 'timingRule', 'allocationRule', 'rebalanceCalendar', 'costModel'],
    outputViews: ['策略配置摘要', '标的池与交易约束', '择时/配置规则', '保存草案'],
    logicNotes: '先前台保存配置口径，不执行交易；后续回测工具读取同一配置对象。',
  },
  {
    capabilityId: 'lab.transaction_strategy_config',
    title: '交易策略配置工具',
    requirementRef: '2.2',
    status: 'native_shell_ready',
    inputRefs: ['snapshotRecord', 'benchmarkId', 'cashFlowRule'],
    configFields: ['interval', 'frequency', 'amount', 'benchmarkId', 'buyRule', 'pauseRule', 'sellRule'],
    outputViews: ['定投/再平衡参数', '现金流计划', '基准比较口径'],
    logicNotes: '三档月度定投、区间、频率、金额和基准都以配置保存；不隐式读取旧回测结果。',
  },
  {
    capabilityId: 'lab.portfolio_metrics_compare',
    title: '组合核心指标展示与对比',
    requirementRef: '2.3',
    status: 'contract_ready',
    inputRefs: ['resultArtifactRecord'],
    configFields: ['annualizedReturn', 'volatility', 'maxDrawdown', 'sharpe', 'calmar', 'turnover', 'hitRate', 'informationRatio'],
    outputViews: ['组合指标卡', '策略/基准对比表', '同口径比较提示'],
    logicNotes: '只比较同snapshot、同基准、同成本、同调仓日历的结果。',
  },
  {
    capabilityId: 'lab.account_curve_compare',
    title: '账户收益率、账户价值与净值展示',
    requirementRef: '2.4',
    status: 'contract_ready',
    inputRefs: ['portfolioSeries', 'cashFlowSeries', 'benchmarkSeries'],
    configFields: ['accountValue', 'unitNav', 'timeWeightedReturn', 'moneyWeightedReturn', 'drawdown'],
    outputViews: ['账户价值曲线', '单位净值曲线', '收益率对比', '回撤曲线'],
    logicNotes: 'TWR和IRR分开展示，定投策略必须保留现金流口径。',
  },
  {
    capabilityId: 'lab.custom_factor_builder',
    title: '因子策略自建工具',
    requirementRef: '2.5',
    status: 'native_shell_ready',
    inputRefs: ['factorLibraryRecord', 'factorDefinitionRecord'],
    configFields: ['customFormula', 'weightingRule', 'winsorization', 'neutralization', 'missingValuePolicy', 'riskTags'],
    outputViews: ['自建因子表单', '字段/公式校验', '保存到因子库'],
    logicNotes: '自建因子先进入因子库和实验配置，不直接变成有效策略结论。',
  },
  {
    capabilityId: 'lab.factor_positioning_map',
    title: '配置因子定位图',
    requirementRef: '2.6',
    status: 'contract_ready',
    inputRefs: ['experimentRecord', 'factorScoreSeries'],
    configFields: ['factorScore', 'valuationPercentile', 'momentumRank', 'crowdingPenalty', 'riskBucket'],
    outputViews: ['二维定位图', '分位/拥挤提示', '当前配置位置说明'],
    logicNotes: '定位图展示当下因子暴露和分位，不等同于交易建议。',
  },
  {
    capabilityId: 'lab.factor_scoring_backtest_logic',
    title: '择时、配置与因子层打分展示',
    requirementRef: '2.7',
    status: 'contract_ready',
    inputRefs: ['factorScoreSeries', 'timingDefinitions', 'experimentRecord'],
    configFields: ['scoreFormula', 'timingGate', 'allocationBucket', 'rebalanceRule'],
    outputViews: ['因子打分卡', '择时闸门', '配置权重解释', '回测逻辑说明'],
    logicNotes: '择时、配置和横截面排序分层展示，避免把Beta闸门误读成Alpha因子。',
  },
  {
    capabilityId: 'lab.alpha_smart_beta_attribution',
    title: 'Alpha / Smart Beta / 残差业绩归因',
    requirementRef: '2.8',
    status: 'contract_ready',
    inputRefs: ['resultArtifactRecord', 'factorExposureSeries', 'benchmarkSeries'],
    configFields: ['betaReturn', 'smartBetaReturn', 'alphaReturn', 'residualReturn', 'timeEffect', 'selectionEffect'],
    outputViews: ['超额收益拆解', '时间因素/非时间因素归因', '残差说明'],
    logicNotes: '归因要把基准Beta、Smart Beta暴露、主动Alpha和残差项分开，并标注无法解释部分。',
  },
  {
    capabilityId: 'lab.backtest_error_risk_attribution',
    title: '回测误差与风险归因说明',
    requirementRef: '2.9',
    status: 'contract_ready',
    inputRefs: ['resultArtifactRecord', 'dataQualityReport'],
    configFields: ['lookaheadRisk', 'survivorshipRisk', 'liquidityError', 'rebalanceError', 'costError', 'sampleError'],
    outputViews: ['误差清单', '风险归因表', '计算逻辑说明'],
    logicNotes: '默认承认回测误差存在；每个结果必须说明数据、成本、调仓、样本和幸存者偏差风险。',
  },
  {
    capabilityId: 'lab.sensitivity_data_scope_notes',
    title: '敏感度与数据口径说明',
    requirementRef: '2.10',
    status: 'contract_ready',
    inputRefs: ['sensitivity_grid', 'snapshotRecord'],
    configFields: ['parameterSweep', 'dataScope', 'frequency', 'missingValuePolicy', 'vendorBoundary', 'sampleWindow'],
    outputViews: ['敏感度网格', '参数旋钮说明', '数据口径备注'],
    logicNotes: '敏感度用于识别参数依赖，不用于挑选最优历史参数直接上线。',
  },
];

export const factorStrategyTemplates = [
  {
    strategyTemplateId: 'strategy.factor_rotation_topn',
    title: '因子轮动 TopN 配置策略',
    strategyType: 'factor_rotation',
    targetUniverse: 'sw_industry_and_etf_proxy',
    tradeInstrument: 'industry_index_or_etf_proxy',
    factorFamilyIds: ['library.industry.value', 'library.industry.momentum', 'library.industry.growth_quality', 'library.industry.crowding_risk'],
    timingLayer: ['timing.pe_decile_gate', 'timing.macro_pmi_m2_shibor'],
    allocationLayer: 'top_n_equal_or_score_weighted',
    benchmarkId: 'factors.etf_smartbeta.bench',
    requiredConfig: ['snapshotId', 'topN', 'rebalanceCalendar', 'costModel', 'comparisonLimits'],
    outputNeeds: ['portfolio_metrics', 'account_curve', 'factor_positioning_map', 'alpha_smart_beta_attribution', 'sensitivity_grid'],
  },
  {
    strategyTemplateId: 'strategy.monthly_dca_three_bucket',
    title: '三档月度定投策略',
    strategyType: 'dca',
    targetUniverse: 'broad_index_or_industry_proxy',
    tradeInstrument: 'index_or_etf_proxy',
    factorFamilyIds: ['library.industry.low_volatility', 'library.industry.dividend', 'library.industry.size_liquidity'],
    timingLayer: ['timing.pe_decile_gate'],
    allocationLayer: 'cash_flow_bucket_a_b_c',
    benchmarkId: 'broad_or_strategy_specific_benchmark',
    requiredConfig: ['startDate', 'endDate', 'frequency', 'amount', 'buyRule', 'pauseRule', 'benchmarkId'],
    outputNeeds: ['cash_flow_schedule', 'money_weighted_return', 'time_weighted_return', 'account_value_curve', 'drawdown_curve'],
  },
  {
    strategyTemplateId: 'strategy.fund_cross_section_screen',
    title: '基金横截面筛选策略',
    strategyType: 'fund_screen',
    targetUniverse: 'public_funds',
    tradeInstrument: 'fund_share_class',
    factorFamilyIds: ['library.fund.absolute_performance', 'library.fund.benchmark_relative', 'library.fund.fees_cost', 'library.fund.manager_product_structure'],
    timingLayer: [],
    allocationLayer: 'rank_filter_review',
    benchmarkId: 'fund_mapped_benchmark',
    requiredConfig: ['snapshotId', 'strategyTypeFilter', 'primaryShareOnly', 'factorWeights', 'feePolicy', 'comparisonLimits'],
    outputNeeds: ['factor_score_table', 'peer_compare', 'data_scope_notes', 'risk_flags'],
  },
  {
    strategyTemplateId: 'strategy.custom_factor_lab',
    title: '自建因子策略实验',
    strategyType: 'custom_factor',
    targetUniverse: 'selected_by_user',
    tradeInstrument: 'configured_by_user',
    factorFamilyIds: [],
    timingLayer: [],
    allocationLayer: 'user_defined',
    benchmarkId: 'configured_by_user',
    requiredConfig: ['customFormula', 'fieldDefinitions', 'snapshotId', 'weightingRule', 'validationNotes'],
    outputNeeds: ['definition_inventory', 'subfactor_usage', 'sensitivity_grid', 'error_attribution'],
  },
];

export const factorResultViewSpecs = [
  {
    viewId: 'view.portfolio_metrics',
    title: 'Portfolio 核心指标',
    metrics: ['annualizedReturn', 'volatility', 'maxDrawdown', 'sharpe', 'calmar', 'turnover', 'hitRate', 'informationRatio'],
    compareBy: ['benchmarkId', 'strategyTemplateId', 'configId'],
    notes: '指标展示必须带上snapshot、成本、调仓日历和基准。',
  },
  {
    viewId: 'view.account_curves',
    title: '账户价值、净值与收益率',
    metrics: ['accountValue', 'unitNav', 'timeWeightedReturn', 'moneyWeightedReturn', 'drawdown'],
    compareBy: ['strategy', 'benchmark', 'cashFlowPolicy'],
    notes: '有现金流的定投策略必须同时展示TWR和IRR，不能只给净值线。',
  },
  {
    viewId: 'view.factor_positioning',
    title: '当前配置因子定位图',
    metrics: ['factorScore', 'valuationPercentile', 'momentumRank', 'crowdingPenalty', 'riskBucket'],
    compareBy: ['asOfDate', 'universe', 'factorFamilyId'],
    notes: '定位图只说明当前暴露和相对分位，不直接给买卖结论。',
  },
  {
    viewId: 'view.attribution',
    title: 'Alpha / Smart Beta / 残差归因',
    metrics: ['betaReturn', 'smartBetaReturn', 'alphaReturn', 'residualReturn', 'timeEffect', 'selectionEffect'],
    compareBy: ['period', 'factorFamilyId', 'benchmarkId'],
    notes: '残差必须保留，不把无法解释的收益强行归到Alpha。',
  },
  {
    viewId: 'view.error_sensitivity',
    title: '误差、风险归因与敏感度',
    metrics: ['lookaheadRisk', 'survivorshipRisk', 'liquidityError', 'costError', 'parameterSensitivity', 'sampleWindowSensitivity'],
    compareBy: ['parameter', 'dataScope', 'sampleWindow'],
    notes: '每次回测都要说明误差来源、数据口径和敏感度边界。',
  },
];

export const commonFactorLibrary = [
  {
    factorFamilyId: 'library.industry.value',
    module: 'factors',
    title: '行业价值因子族',
    universe: 'sw_industry_and_etf_proxy',
    category: 'value',
    frequency: 'monthly_rebalance_from_daily_panel',
    sourceAssetIds: ['factors.etf_smartbeta.panel'],
    snapshotIds: ['snapshot.etf_smartbeta.industry_panel.current', 'snapshot.etf_smartbeta.industry_execution.current'],
    status: 'mapped_from_source',
    version: 'library-v1',
    notes: '来自旧ETF/行业面板和factor_registry；适用于行业横截面，不直接用于基金份额排序。',
    fields: [
      { field: 'f_bm', name: 'BM 账面市值比', role: 'sub_factor', formula: 'zscore(1 / PB)', direction: 'higher_is_better', missingValuePolicy: 'pb<=0 is missing; fill 0 inside composite only', status: 'mapped_from_source' },
      { field: 'f_ep', name: 'EP 盈利收益率', role: 'sub_factor', formula: 'zscore(1 / PE)', direction: 'higher_is_better', missingValuePolicy: 'pe<=0 is missing; fill 0 inside composite only', status: 'mapped_from_source' },
      { field: 'f_pbpct', name: 'PB 历史分位反向', role: 'sub_factor', formula: 'zscore(1 - rolling_pct(PB, 756))', direction: 'higher_is_better', missingValuePolicy: 'requires at least rolling window minimum', status: 'mapped_from_source' },
      { field: 'f_pepct', name: 'PE 历史分位反向', role: 'sub_factor', formula: 'zscore(1 - rolling_pct(PE, 756))', direction: 'higher_is_better', missingValuePolicy: 'requires at least rolling window minimum', status: 'mapped_from_source' },
      { field: 'F_value', name: '价值综合分', role: 'composite', formula: '0.45*f_bm + 0.20*f_ep + 0.25*f_pbpct + 0.10*f_pepct', direction: 'higher_is_better', missingValuePolicy: 'sub-factor missing filled with 0 after zscore', status: 'mapped_from_source' },
    ],
  },
  {
    factorFamilyId: 'library.industry.momentum',
    module: 'factors',
    title: '行业动量因子族',
    universe: 'sw_industry_and_etf_proxy',
    category: 'momentum',
    frequency: 'monthly_rebalance_from_daily_panel',
    sourceAssetIds: ['factors.etf_smartbeta.panel'],
    snapshotIds: ['snapshot.etf_smartbeta.industry_panel.current', 'snapshot.etf_smartbeta.industry_execution.current'],
    status: 'mapped_from_source',
    version: 'library-v1',
    notes: '动量窗口均只使用调仓日前可见价格；短期窗口可用于诊断，不默认进入综合分。',
    fields: [
      { field: 'mom_12_1', name: '12-1 动量原值', role: 'raw_signal', formula: 'close.shift(21) / close.shift(252) - 1', direction: 'higher_is_better', missingValuePolicy: 'insufficient history is missing', status: 'mapped_from_source' },
      { field: 'mom_6_1', name: '6-1 动量原值', role: 'raw_signal', formula: 'close.shift(21) / close.shift(126) - 1', direction: 'higher_is_better', missingValuePolicy: 'insufficient history is missing', status: 'mapped_from_source' },
      { field: 'mom_3', name: '3月动量原值', role: 'diagnostic_signal', formula: 'close / close.shift(63) - 1', direction: 'higher_is_better', missingValuePolicy: 'insufficient history is missing', status: 'candidate' },
      { field: 'mom_1', name: '1月动量原值', role: 'diagnostic_signal', formula: 'close / close.shift(21) - 1', direction: 'context_dependent', missingValuePolicy: 'insufficient history is missing', status: 'candidate' },
      { field: 'F_mom', name: '动量综合分', role: 'composite', formula: '0.65*zscore(mom_12_1) + 0.35*zscore(mom_6_1)', direction: 'higher_is_better', missingValuePolicy: 'sub-factor missing filled with 0 after zscore', status: 'mapped_from_source' },
    ],
  },
  {
    factorFamilyId: 'library.industry.growth_quality',
    module: 'factors',
    title: '行业景气与质量因子族',
    universe: 'sw_industry_and_etf_proxy',
    category: 'growth',
    frequency: 'monthly_rebalance_from_daily_panel',
    sourceAssetIds: ['factors.etf_smartbeta.panel'],
    snapshotIds: ['snapshot.etf_smartbeta.industry_panel.current', 'snapshot.etf_smartbeta.industry_execution.current'],
    status: 'mapped_from_source',
    version: 'library-v1',
    notes: 'EPS/BPS由价格与估值反推，必须保留发布滞后和前视风险标记。',
    fields: [
      { field: 'f_eg', name: '盈利同比增速', role: 'sub_factor', formula: 'zscore(EPS(t) / EPS(t-244) - 1)', direction: 'higher_is_better', missingValuePolicy: 'pe<=0 or insufficient history is missing', status: 'mapped_from_source' },
      { field: 'f_egq', name: '盈利环比动能', role: 'sub_factor', formula: 'zscore(EPS(t) / EPS(t-61) - 1)', direction: 'higher_is_better', missingValuePolicy: 'pe<=0 or insufficient history is missing', status: 'mapped_from_source' },
      { field: 'f_eacc', name: '盈利加速度', role: 'sub_factor', formula: 'zscore(earn_growth - earn_growth.shift(61))', direction: 'higher_is_better', missingValuePolicy: 'requires earn_growth history', status: 'mapped_from_source' },
      { field: 'f_bps', name: 'BPS 增长', role: 'sub_factor', formula: 'zscore(BPS(t) / BPS(t-244) - 1)', direction: 'higher_is_better', missingValuePolicy: 'pb<=0 or insufficient history is missing', status: 'mapped_from_source' },
      { field: 'F_prosper', name: '景气综合分', role: 'composite', formula: '0.40*f_eg + 0.25*f_egq + 0.20*f_eacc + 0.15*f_bps', direction: 'higher_is_better', missingValuePolicy: 'sub-factor missing filled with 0 after zscore', status: 'mapped_from_source' },
    ],
  },
  {
    factorFamilyId: 'library.industry.crowding_risk',
    module: 'factors',
    title: '行业拥挤与风险因子族',
    universe: 'sw_industry_and_etf_proxy',
    category: 'sentiment',
    frequency: 'monthly_rebalance_from_daily_panel',
    sourceAssetIds: ['factors.etf_smartbeta.panel'],
    snapshotIds: ['snapshot.etf_smartbeta.industry_panel.current', 'snapshot.etf_smartbeta.industry_execution.current'],
    status: 'mapped_from_source',
    version: 'library-v1',
    notes: '拥挤度默认是惩罚项；风险字段可用于过滤、约束或归因，不默认提高排序。',
    fields: [
      { field: 'f_turn', name: '换手率分位', role: 'sub_factor', formula: 'zscore(rolling_pct(turnover, 756))', direction: 'lower_is_better', missingValuePolicy: 'insufficient history is missing', status: 'mapped_from_source' },
      { field: 'f_amt', name: '成交额占比分位', role: 'sub_factor', formula: 'zscore(rolling_pct(amt_share, 504))', direction: 'lower_is_better', missingValuePolicy: 'insufficient history is missing', status: 'mapped_from_source' },
      { field: 'f_expand', name: '估值扩张', role: 'sub_factor', formula: 'zscore(PB(t) / PB(t-252) - 1)', direction: 'lower_is_better', missingValuePolicy: 'pb<=0 or insufficient history is missing', status: 'mapped_from_source' },
      { field: 'f_accel', name: '动量二阶', role: 'sub_factor', formula: 'zscore(mom_3 - mom_12_1 * 63 / 231)', direction: 'lower_is_better', missingValuePolicy: 'requires momentum history', status: 'mapped_from_source' },
      { field: 'vol_60', name: '60日年化波动', role: 'risk_control', formula: 'std(daily_return, 60) * sqrt(244)', direction: 'lower_is_better', missingValuePolicy: 'requires at least 40 observations', status: 'candidate' },
      { field: 'F_crowd', name: '拥挤综合分', role: 'composite_penalty', formula: '0.35*f_turn + 0.25*f_amt + 0.25*f_expand + 0.15*f_accel', direction: 'lower_is_better', missingValuePolicy: 'sub-factor missing filled with 0 after zscore', status: 'mapped_from_source' },
    ],
  },
  {
    factorFamilyId: 'library.fund.absolute_performance',
    module: 'factors',
    title: '基金绝对收益与风险因子族',
    universe: 'public_funds',
    category: 'performance',
    frequency: 'latest_cross_section_from_nav_history',
    sourceAssetIds: ['factors.fund_warehouse.wide_today', 'factors.fund_warehouse.fof_db'],
    snapshotIds: ['snapshot.fund_warehouse.wide_today.current'],
    status: 'mapped_from_source',
    version: 'library-v1',
    notes: '来自基金宽表；日频与周频基金必须按freq_used分组比较。',
    fields: [
      { field: '年化收益_pct', name: '成立以来年化收益', role: 'return_metric', formula: 'annualized total return since data start', direction: 'higher_is_better', missingValuePolicy: 'requires at least two observations', status: 'mapped_from_source' },
      { field: '近1年收益_pct', name: '近1年收益', role: 'return_metric', formula: 'trailing 365-day return', direction: 'higher_is_better', missingValuePolicy: 'insufficient history is missing', status: 'mapped_from_source' },
      { field: '成立来最大回撤_pct', name: '成立以来最大回撤', role: 'risk_metric', formula: 'min(nav / cumulative_max(nav) - 1)', direction: 'higher_is_better', missingValuePolicy: 'requires NAV history', status: 'mapped_from_source' },
      { field: '夏普_成立来', name: '成立以来夏普', role: 'risk_adjusted_metric', formula: '(annualized_return - RF_ANNUAL) / annualized_volatility', direction: 'higher_is_better', missingValuePolicy: 'zero volatility or missing return is missing', status: 'mapped_from_source' },
      { field: '索提诺', name: '索提诺', role: 'risk_adjusted_metric', formula: '(annualized_return - RF_ANNUAL) / downside_volatility', direction: 'higher_is_better', missingValuePolicy: 'zero downside volatility is missing', status: 'mapped_from_source' },
      { field: '卡玛', name: '卡玛', role: 'risk_adjusted_metric', formula: 'annualized_return / abs(max_drawdown)', direction: 'higher_is_better', missingValuePolicy: 'zero or missing drawdown is missing', status: 'mapped_from_source' },
      { field: '月度胜率_pct', name: '月度胜率', role: 'stability_metric', formula: 'share of positive monthly returns', direction: 'higher_is_better', missingValuePolicy: 'requires at least 6 monthly observations', status: 'mapped_from_source' },
    ],
  },
  {
    factorFamilyId: 'library.fund.benchmark_relative',
    module: 'factors',
    title: '基金基准相对因子族',
    universe: 'public_funds',
    category: 'relative_performance',
    frequency: 'latest_cross_section_from_nav_history',
    sourceAssetIds: ['factors.fund_warehouse.wide_today', 'factors.fund_warehouse.fof_db'],
    snapshotIds: ['snapshot.fund_warehouse.wide_today.current'],
    status: 'mapped_from_source',
    version: 'library-v1',
    notes: '主动基金、被动指数和指数增强不能混用同一相对指标排序；价格口径基准必须标注。',
    fields: [
      { field: '超额年化_pct', name: '对齐区间超额年化', role: 'relative_return_metric', formula: 'fund annualized return - benchmark annualized return on aligned interval', direction: 'higher_is_better', missingValuePolicy: 'requires mapped benchmark and aligned history', status: 'mapped_from_source' },
      { field: '跟踪误差_pct', name: '跟踪误差', role: 'relative_risk_metric', formula: 'std(fund_return - benchmark_return) * sqrt(freq_ann)', direction: 'lower_is_better', missingValuePolicy: 'only for passive/enhanced benchmark tracking funds', status: 'mapped_from_source' },
      { field: '信息比率', name: '信息比率', role: 'risk_adjusted_relative_metric', formula: 'excess_annualized_return / tracking_error', direction: 'higher_is_better', missingValuePolicy: 'requires tracking_error > 0', status: 'mapped_from_source' },
      { field: '月度超额胜率_pct', name: '月度超额胜率', role: 'relative_stability_metric', formula: 'share of months where fund_return > benchmark_return', direction: 'higher_is_better', missingValuePolicy: 'requires at least 12 aligned months', status: 'mapped_from_source' },
      { field: '上行捕获_pct', name: '上行捕获', role: 'regime_metric', formula: 'mean fund monthly return / mean benchmark monthly return when benchmark > 0', direction: 'context_dependent', missingValuePolicy: 'requires at least 6 up months', status: 'mapped_from_source' },
      { field: '下行捕获_pct', name: '下行捕获', role: 'regime_metric', formula: 'mean fund monthly return / mean benchmark monthly return when benchmark < 0', direction: 'lower_is_better', missingValuePolicy: 'requires at least 6 down months', status: 'mapped_from_source' },
    ],
  },
  {
    factorFamilyId: 'library.fund.holdings_structure',
    module: 'factors',
    title: '基金持仓结构与漂移因子族',
    universe: 'public_funds',
    category: 'portfolio_structure',
    frequency: 'quarterly_or_latest_available',
    sourceAssetIds: ['factors.fund_warehouse.wide_today', 'factors.fund_warehouse.fof_db'],
    snapshotIds: ['snapshot.fund_warehouse.wide_today.current'],
    status: 'mapped_from_source',
    version: 'library-v1',
    notes: '持仓和费率更新频率低于净值；用于过滤、解释和风险控制，不默认当作收益预测因子。',
    fields: [
      { field: 'stock_pct', name: '股票仓位', role: 'exposure_metric', formula: 'latest holdings stock percentage', direction: 'context_dependent', missingValuePolicy: 'quarterly holding missing remains missing', status: 'mapped_from_source' },
      { field: 'industry_hhi', name: '行业集中度 HHI', role: 'concentration_metric', formula: 'sum(industry_weight^2)', direction: 'lower_is_better', missingValuePolicy: 'requires holdings classification', status: 'mapped_from_source' },
      { field: 'top10_conc', name: '前十大集中度', role: 'concentration_metric', formula: 'sum top 10 holdings weight', direction: 'lower_is_better', missingValuePolicy: 'requires holdings details', status: 'mapped_from_source' },
      { field: 'top_industry', name: '第一大行业', role: 'classification', formula: 'industry with largest holdings weight', direction: 'not_ranked', missingValuePolicy: 'requires holdings classification', status: 'mapped_from_source' },
      { field: 'drift_mean', name: '平均风格漂移', role: 'style_drift_metric', formula: 'mean distance from inferred style benchmark', direction: 'lower_is_better', missingValuePolicy: 'requires drift scan output', status: 'mapped_from_source' },
      { field: 'drift_max', name: '最大风格漂移', role: 'style_drift_metric', formula: 'max distance from inferred style benchmark', direction: 'lower_is_better', missingValuePolicy: 'requires drift scan output', status: 'mapped_from_source' },
    ],
  },
  {
    factorFamilyId: 'library.industry.low_volatility',
    module: 'factors',
    title: '行业低波与防御因子族',
    universe: 'sw_industry_and_etf_proxy',
    category: 'low_volatility',
    frequency: 'monthly_rebalance_from_daily_panel',
    sourceAssetIds: ['factors.etf_smartbeta.panel', 'factors.etf_smartbeta.bench'],
    snapshotIds: ['snapshot.etf_smartbeta.industry_panel.current', 'snapshot.etf_smartbeta.industry_execution.current'],
    status: 'candidate',
    version: 'library-v1',
    notes: '低波类因子常用于防御、风险平价和组合约束；收益方向依赖市场状态，默认先作为风险/稳定性维度登记。',
    fields: [
      { field: 'vol_20', name: '20日年化波动', role: 'risk_metric', formula: 'std(daily_return, 20) * sqrt(244)', direction: 'lower_is_better', missingValuePolicy: 'requires at least 15 observations', status: 'candidate' },
      { field: 'vol_60', name: '60日年化波动', role: 'risk_metric', formula: 'std(daily_return, 60) * sqrt(244)', direction: 'lower_is_better', missingValuePolicy: 'requires at least 40 observations', status: 'mapped_from_source' },
      { field: 'downside_vol_60', name: '60日下行波动', role: 'risk_metric', formula: 'std(min(daily_return, 0), 60) * sqrt(244)', direction: 'lower_is_better', missingValuePolicy: 'requires enough negative-return observations', status: 'candidate' },
      { field: 'beta_hs300_252', name: '沪深300一年滚动Beta', role: 'market_exposure', formula: 'cov(industry_return, hs300_return, 252) / var(hs300_return, 252)', direction: 'context_dependent', missingValuePolicy: 'requires aligned benchmark return history', status: 'candidate' },
      { field: 'max_drawdown_252', name: '一年滚动最大回撤', role: 'tail_risk_metric', formula: 'min(nav / rolling_max(nav, 252) - 1)', direction: 'higher_is_better', missingValuePolicy: 'requires 252 trading days', status: 'candidate' },
    ],
  },
  {
    factorFamilyId: 'library.industry.dividend',
    module: 'factors',
    title: '行业红利与股息因子族',
    universe: 'sw_industry_and_etf_proxy',
    category: 'dividend',
    frequency: 'monthly_rebalance_from_daily_panel',
    sourceAssetIds: ['factors.etf_smartbeta.panel'],
    snapshotIds: ['snapshot.etf_smartbeta.industry_panel.current', 'snapshot.etf_smartbeta.industry_execution.current'],
    status: 'candidate',
    version: 'library-v1',
    notes: '红利因子需要区分股息率、股息稳定性和高股息陷阱；行业层面先登记可从面板派生的候选字段。',
    fields: [
      { field: 'div_yield', name: '股息率', role: 'income_metric', formula: 'panel.div_yield', direction: 'higher_is_better', missingValuePolicy: 'missing or non-positive dividend yield remains missing', status: 'mapped_from_source' },
      { field: 'div_yield_pct_3y', name: '股息率三年历史分位', role: 'valuation_anchor', formula: 'rolling_pct(div_yield, 756)', direction: 'higher_is_better', missingValuePolicy: 'requires rolling history', status: 'candidate' },
      { field: 'div_yield_stability_3y', name: '股息率稳定性', role: 'quality_metric', formula: '-std(div_yield, 756)', direction: 'higher_is_better', missingValuePolicy: 'requires rolling dividend history', status: 'candidate' },
      { field: 'dividend_value_combo', name: '红利价值组合分', role: 'composite', formula: 'zscore(div_yield) + zscore(1 - pb_pct)', direction: 'higher_is_better', missingValuePolicy: 'requires dividend yield and valuation history', status: 'candidate' },
    ],
  },
  {
    factorFamilyId: 'library.industry.size_liquidity',
    module: 'factors',
    title: '行业规模与流动性因子族',
    universe: 'sw_industry_and_etf_proxy',
    category: 'size',
    frequency: 'monthly_rebalance_from_daily_panel',
    sourceAssetIds: ['factors.etf_smartbeta.panel'],
    snapshotIds: ['snapshot.etf_smartbeta.industry_panel.current', 'snapshot.etf_smartbeta.industry_execution.current'],
    status: 'candidate',
    version: 'library-v1',
    notes: '行业层面的规模不是个股市值因子，需要结合成交占比、可投资ETF承载和行业容量解释。',
    fields: [
      { field: 'amt_share', name: '成交额占比', role: 'liquidity_metric', formula: 'industry amount / total market amount', direction: 'context_dependent', missingValuePolicy: 'missing trading amount remains missing', status: 'mapped_from_source' },
      { field: 'amt_share_pct', name: '成交额占比分位', role: 'liquidity_regime_metric', formula: 'rolling_pct(amt_share, 504)', direction: 'context_dependent', missingValuePolicy: 'requires rolling history', status: 'mapped_from_source' },
      { field: 'turnover', name: '换手率', role: 'liquidity_metric', formula: 'panel.turnover', direction: 'context_dependent', missingValuePolicy: 'missing turnover remains missing', status: 'mapped_from_source' },
      { field: 'turnover_pct', name: '换手率分位', role: 'liquidity_regime_metric', formula: 'rolling_pct(turnover, 756)', direction: 'context_dependent', missingValuePolicy: 'requires rolling history', status: 'mapped_from_source' },
      { field: 'investable_capacity_flag', name: 'ETF可投资容量标记', role: 'investability_filter', formula: 'derived from investable universe and ETF availability', direction: 'higher_is_better', missingValuePolicy: 'missing investability data means not eligible by default', status: 'candidate' },
    ],
  },
  {
    factorFamilyId: 'library.fund.fees_cost',
    module: 'factors',
    title: '基金费用与交易成本因子族',
    universe: 'public_funds',
    category: 'fees',
    frequency: 'monthly_refresh_with_quarterly_fee_update',
    sourceAssetIds: ['factors.fund_warehouse.wide_today', 'factors.fund_warehouse.fof_db'],
    snapshotIds: ['snapshot.fund_warehouse.wide_today.current'],
    status: 'candidate',
    version: 'library-v1',
    notes: '费用字段适合做长期收益侵蚀、产品筛选和同类比较；不同份额类型和销售费率需要分开处理。',
    fields: [
      { field: '管理费率_pct', name: '管理费率', role: 'fee_metric', formula: 'latest management fee percentage', direction: 'lower_is_better', missingValuePolicy: 'missing fee remains missing', status: 'candidate' },
      { field: '托管费率_pct', name: '托管费率', role: 'fee_metric', formula: 'latest custodian fee percentage', direction: 'lower_is_better', missingValuePolicy: 'missing fee remains missing', status: 'candidate' },
      { field: '销售服务费率_pct', name: '销售服务费率', role: 'fee_metric', formula: 'latest sales service fee percentage for share class', direction: 'lower_is_better', missingValuePolicy: 'missing fee remains missing; share classes are not merged', status: 'candidate' },
      { field: '综合费率_pct', name: '综合费率', role: 'fee_composite', formula: 'management_fee + custodian_fee + sales_service_fee', direction: 'lower_is_better', missingValuePolicy: 'requires at least one fee component and explicit missing component policy', status: 'candidate' },
      { field: '费用后信息比率', name: '费用后信息比率', role: 'fee_adjusted_metric', formula: '(excess_annualized_return - total_fee) / tracking_error', direction: 'higher_is_better', missingValuePolicy: 'requires total fee and tracking_error > 0', status: 'candidate' },
    ],
  },
  {
    factorFamilyId: 'library.fund.manager_product_structure',
    module: 'factors',
    title: '基金经理与产品结构因子族',
    universe: 'public_funds',
    category: 'manager_product_structure',
    frequency: 'monthly_or_quarterly_profile_refresh',
    sourceAssetIds: ['factors.fund_warehouse.wide_today', 'factors.fund_warehouse.fof_db'],
    snapshotIds: ['snapshot.fund_warehouse.wide_today.current'],
    status: 'candidate',
    version: 'library-v1',
    notes: '基金经理与产品结构是开放式重点：先登记可研究字段，后续接入基金经理任职、规模、产品线和风格稳定性数据后再计算。',
    fields: [
      { field: 'manager_tenure_days', name: '基金经理任职天数', role: 'manager_stability_metric', formula: 'as_of_date - manager_start_date', direction: 'context_dependent', missingValuePolicy: 'missing manager start date remains missing', status: 'candidate' },
      { field: 'manager_product_count', name: '基金经理在管产品数', role: 'manager_capacity_metric', formula: 'count active products per manager', direction: 'context_dependent', missingValuePolicy: 'requires manager-product mapping', status: 'candidate' },
      { field: 'manager_aum_total', name: '基金经理在管规模', role: 'manager_capacity_metric', formula: 'sum latest AUM across active products per manager', direction: 'context_dependent', missingValuePolicy: 'requires latest AUM and manager mapping', status: 'candidate' },
      { field: 'fund_age_years', name: '产品成立年限', role: 'product_maturity_metric', formula: 'as_of_date - fund_inception_date in years', direction: 'context_dependent', missingValuePolicy: 'missing inception date remains missing', status: 'candidate' },
      { field: 'share_class_primary_flag', name: '主份额标记', role: 'share_class_filter', formula: 'is_primary from fund warehouse universe', direction: 'not_ranked', missingValuePolicy: 'missing flag means review before ranking', status: 'mapped_from_source' },
    ],
  },
];
